// Generated by Generator from config.xml. Do not edit by hand.
#ifndef SIMD_FIX_CONFIG_HPP
#define SIMD_FIX_CONFIG_HPP

#include <string_view>
#include <unordered_map>
#include <variant>

#include "org/limitless/fix/config/FixEngine.hpp"
#include "org/limitless/fix/session/ClientSession.hpp"
#include "org/limitless/fix/session/ServerSession.hpp"
#include "org/limitless/fix/storage/MemoryStorage.hpp"

namespace org::limitless::fix::config {

using namespace org::limitless::fix::session;

using AlphaSession = ServerSession<FIXT_1_1, "ENGINE", "AAA", storage::MemoryStorage, DiscardTransport, RejectApplication>;
using BetaSession = ServerSession<FIXT_1_1, "ENGINE", "BBB", storage::NullStorage, DiscardTransport, RejectApplication>;
using GammaSession = ClientSession<FIXT_1_1, "ENGINE", "VENUE", storage::NullStorage, DiscardTransport, RejectApplication>;

using AnySession = std::variant<AlphaSession, BetaSession, GammaSession>;

[[nodiscard]] inline std::unordered_map<std::string_view, AnySession> sessions()
{
    std::unordered_map<std::string_view, AnySession> registry;
    registry.emplace("alpha", AlphaSession::Builder{storage::MemoryStorage{}}.heartbeatPeriod(std::chrono::milliseconds{30000}).build());
    registry.emplace("beta", BetaSession{});
    registry.emplace("gamma", GammaSession{});
    return registry;
}

} // namespace org::limitless::fix::config

#endif //SIMD_FIX_CONFIG_HPP
