// Generated by Generator from config.xml. Do not edit by hand.
#ifndef SIMD_FIX_ENGINE_HPP
#define SIMD_FIX_ENGINE_HPP

#include <chrono>
#include <cstdint>

#include "org/limitless/fix/Types.hpp"

namespace org::limitless::fix::config {

inline constexpr FixedString EngineCompId{"ENGINE"};
inline constexpr std::uint32_t MaxMessageSize = 4096;
inline constexpr std::uint32_t MaxFields = 256;
inline constexpr std::chrono::milliseconds KeepAlivePeriod{100};
inline constexpr std::chrono::milliseconds HeartbeatPeriod{10000};

} // namespace org::limitless::fix::config

#endif //SIMD_FIX_ENGINE_HPP
