// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_DECODERS_HPP
#define SIMD_FIX_MESSAGE_DECODERS_HPP

#include <expected>

#include "org/limitless/fix/decoder/DataDecoder.hpp"
#include "org/limitless/fix/decoder/GroupDecoder.hpp"
#include "org/limitless/fix/decoder/MessageDecoder.hpp"
#include "org/limitless/fix/messages/FixTypes.hpp"

namespace org::limitless::fix::messages {

using namespace org::limitless::fix::decoder;

struct NestedGroupDecoder : GroupDecoder
{
    explicit NestedGroupDecoder(FieldDecoder& decoder) : 
        GroupDecoder{decoder}
    {
    }

    NestedGroupDecoder(const NestedGroupDecoder&) = delete;
    NestedGroupDecoder& operator=(const NestedGroupDecoder&) = delete;
    NestedGroupDecoder(NestedGroupDecoder&&) = delete;
    NestedGroupDecoder& operator=(NestedGroupDecoder&&) = delete;

    NestedGroupDecoder& wrap()
    {
        GroupDecoder::wrap<500>();
        return *this;
    }

    NestedGroupDecoder& next()
    {
        GroupDecoder::next();
        return *this;
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> name() const
    {
        return m_decoder.getString<501, true, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> nestedOne() const
    {
        return m_decoder.getUint32<601, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> nestedTwo() const
    {
        return m_decoder.getUint32<602, false, RecordType::Group>();
    }

};

struct HopsDecoder : GroupDecoder
{
private:
    NestedGroupDecoder m_nestedGroup;

public:
    explicit HopsDecoder(FieldDecoder& decoder) : 
        GroupDecoder{decoder},
        m_nestedGroup{decoder}
    {
    }

    HopsDecoder(const HopsDecoder&) = delete;
    HopsDecoder& operator=(const HopsDecoder&) = delete;
    HopsDecoder(HopsDecoder&&) = delete;
    HopsDecoder& operator=(HopsDecoder&&) = delete;

    HopsDecoder& wrap()
    {
        GroupDecoder::wrap<627>();
        return *this;
    }

    HopsDecoder& next()
    {
        GroupDecoder::next();
        return *this;
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> hopCompID() const
    {
        return m_decoder.getString<628, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> hopSendingTime() const
    {
        return m_decoder.getTimestamp<629, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> hopRefID() const
    {
        return m_decoder.getUint32<630, false, RecordType::Group>();
    }

    [[nodiscard]] NestedGroupDecoder& nestedGroup()
    {
        return m_nestedGroup.wrap();
    }

};

struct LogonDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    DataDecoder m_xmlData;

public:
    LogonDecoder() : 
        m_hops{m_decoder},
        m_xmlData{m_decoder}
    {
    }

    LogonDecoder(const LogonDecoder&) = delete;
    LogonDecoder& operator=(const LogonDecoder&) = delete;
    LogonDecoder(LogonDecoder&&) = delete;
    LogonDecoder& operator=(LogonDecoder&&) = delete;

    static constexpr uint8_t MessageId = 'A';

    LogonDecoder& wrap(const std::span<const uint8_t> data,
            const std::span<Token> tokens,
            const std::span<uint16_t> tags,
            const uint32_t count)
    {
        m_decoder.wrap(data, tokens, tags, count);
        return *this;
    }

    void context(const SessionContext* context)
    {
        MessageDecoder::context(context);
    }

    [[nodiscard]] std::expected<Protocol::Values, Result::Values> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result::Values> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> sender() const
    {
        return m_decoder.getString<49, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> target() const
    {
        return m_decoder.getString<56, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> sequenceNumber() const
    {
        return m_decoder.getUint32<34, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> sendingTime() const
    {
        return m_decoder.getTimestamp<52, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<Encryption::Values, Result::Values> encryptMethod() const
    {
        return m_decoder.getEnum<98, false, Encryption, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> heartbeatInterval() const
    {
        return m_decoder.getUint32<108, true, RecordType::Message>();
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

    [[nodiscard]] DataDecoder& xmlData()
    {
        return m_xmlData.wrap<212, 213>();
    }

};

struct LogoutDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

public:
    LogoutDecoder() : 
        m_hops{m_decoder}
    {
    }

    LogoutDecoder(const LogoutDecoder&) = delete;
    LogoutDecoder& operator=(const LogoutDecoder&) = delete;
    LogoutDecoder(LogoutDecoder&&) = delete;
    LogoutDecoder& operator=(LogoutDecoder&&) = delete;

    static constexpr uint8_t MessageId = '5';

    LogoutDecoder& wrap(const std::span<const uint8_t> data,
            const std::span<Token> tokens,
            const std::span<uint16_t> tags,
            const uint32_t count)
    {
        m_decoder.wrap(data, tokens, tags, count);
        return *this;
    }

    void context(const SessionContext* context)
    {
        MessageDecoder::context(context);
    }

    [[nodiscard]] std::expected<Protocol::Values, Result::Values> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result::Values> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> sender() const
    {
        return m_decoder.getString<49, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> target() const
    {
        return m_decoder.getString<56, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> sequenceNumber() const
    {
        return m_decoder.getUint32<34, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> sendingTime() const
    {
        return m_decoder.getTimestamp<52, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> text() const
    {
        return m_decoder.getString<58, true, RecordType::Message>();
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct HeartbeatDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

public:
    HeartbeatDecoder() : 
        m_hops{m_decoder}
    {
    }

    HeartbeatDecoder(const HeartbeatDecoder&) = delete;
    HeartbeatDecoder& operator=(const HeartbeatDecoder&) = delete;
    HeartbeatDecoder(HeartbeatDecoder&&) = delete;
    HeartbeatDecoder& operator=(HeartbeatDecoder&&) = delete;

    static constexpr uint8_t MessageId = '0';

    HeartbeatDecoder& wrap(const std::span<const uint8_t> data,
            const std::span<Token> tokens,
            const std::span<uint16_t> tags,
            const uint32_t count)
    {
        m_decoder.wrap(data, tokens, tags, count);
        return *this;
    }

    void context(const SessionContext* context)
    {
        MessageDecoder::context(context);
    }

    [[nodiscard]] std::expected<Protocol::Values, Result::Values> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result::Values> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> sender() const
    {
        return m_decoder.getString<49, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> target() const
    {
        return m_decoder.getString<56, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> sequenceNumber() const
    {
        return m_decoder.getUint32<34, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> sendingTime() const
    {
        return m_decoder.getTimestamp<52, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> testReqID() const
    {
        return m_decoder.getString<112, false, RecordType::Message>();
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct TestRequestDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

public:
    TestRequestDecoder() : 
        m_hops{m_decoder}
    {
    }

    TestRequestDecoder(const TestRequestDecoder&) = delete;
    TestRequestDecoder& operator=(const TestRequestDecoder&) = delete;
    TestRequestDecoder(TestRequestDecoder&&) = delete;
    TestRequestDecoder& operator=(TestRequestDecoder&&) = delete;

    static constexpr uint8_t MessageId = '1';

    TestRequestDecoder& wrap(const std::span<const uint8_t> data,
            const std::span<Token> tokens,
            const std::span<uint16_t> tags,
            const uint32_t count)
    {
        m_decoder.wrap(data, tokens, tags, count);
        return *this;
    }

    void context(const SessionContext* context)
    {
        MessageDecoder::context(context);
    }

    [[nodiscard]] std::expected<Protocol::Values, Result::Values> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result::Values> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> sender() const
    {
        return m_decoder.getString<49, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> target() const
    {
        return m_decoder.getString<56, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> sequenceNumber() const
    {
        return m_decoder.getUint32<34, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> sendingTime() const
    {
        return m_decoder.getTimestamp<52, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> testReqID() const
    {
        return m_decoder.getString<112, false, RecordType::Message>();
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct NewOrderSingleDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

public:
    NewOrderSingleDecoder() : 
        m_hops{m_decoder}
    {
    }

    NewOrderSingleDecoder(const NewOrderSingleDecoder&) = delete;
    NewOrderSingleDecoder& operator=(const NewOrderSingleDecoder&) = delete;
    NewOrderSingleDecoder(NewOrderSingleDecoder&&) = delete;
    NewOrderSingleDecoder& operator=(NewOrderSingleDecoder&&) = delete;

    static constexpr uint8_t MessageId = 'D';

    NewOrderSingleDecoder& wrap(const std::span<const uint8_t> data,
            const std::span<Token> tokens,
            const std::span<uint16_t> tags,
            const uint32_t count)
    {
        m_decoder.wrap(data, tokens, tags, count);
        return *this;
    }

    void context(const SessionContext* context)
    {
        MessageDecoder::context(context);
    }

    [[nodiscard]] std::expected<Protocol::Values, Result::Values> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result::Values> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> sender() const
    {
        return m_decoder.getString<49, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> target() const
    {
        return m_decoder.getString<56, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> sequenceNumber() const
    {
        return m_decoder.getUint32<34, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> sendingTime() const
    {
        return m_decoder.getTimestamp<52, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> account() const
    {
        return m_decoder.getString<1, false, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> clOrdID() const
    {
        return m_decoder.getString<11, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<HandlInst::Values, Result::Values> handlInst() const
    {
        return m_decoder.getEnum<21, true, HandlInst, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> symbol() const
    {
        return m_decoder.getString<55, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<Side::Values, Result::Values> side() const
    {
        return m_decoder.getEnum<54, true, Side, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result::Values> transactTime() const
    {
        return m_decoder.getTimestamp<60, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result::Values> orderQty() const
    {
        return m_decoder.getUint32<38, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<OrdType::Values, Result::Values> ordType() const
    {
        return m_decoder.getEnum<40, true, OrdType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<utils::FixedDecimal, Result::Values> price() const
    {
        return m_decoder.getFixedDecimal<44, false, RecordType::Message>();
    }

    [[nodiscard]] std::expected<TimeInForce::Values, Result::Values> timeInForce() const
    {
        return m_decoder.getEnum<59, false, TimeInForce, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result::Values> text() const
    {
        return m_decoder.getString<58, false, RecordType::Message>();
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_MESSAGE_DECODERS_HPP
