// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_DECODERS_HPP
#define SIMD_FIX_MESSAGE_DECODERS_HPP

#include <expected>

#include "org/limitless/fix/decoder/DataDecoder.hpp"
#include "org/limitless/fix/decoder/GroupDecoder.hpp"
#include "org/limitless/fix/decoder/MessageDecoder.hpp"
#include "org/limitless/fix/messages/FixTypes.hpp"

namespace org::limitless::fix::messages {

using namespace org::limitless::fix::decoder;

struct NestedGroupDecoder : GroupDecoder
{
    explicit NestedGroupDecoder(FieldDecoder& decoder) : 
        GroupDecoder{decoder}
    {
    }

    NestedGroupDecoder(const NestedGroupDecoder&) = delete;
    NestedGroupDecoder& operator=(const NestedGroupDecoder&) = delete;
    NestedGroupDecoder(NestedGroupDecoder&&) = delete;
    NestedGroupDecoder& operator=(NestedGroupDecoder&&) = delete;

    NestedGroupDecoder& wrap()
    {
        GroupDecoder::wrap<500>();
        return *this;
    }

    NestedGroupDecoder& next()
    {
        GroupDecoder::next();
        return *this;
    }

    [[nodiscard]] std::expected<std::string_view, Result> name() const
    {
        return m_decoder.getString<501, true, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> nestedOne() const
    {
        return m_decoder.getUint32<601, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> nestedTwo() const
    {
        return m_decoder.getUint32<602, false, RecordType::Group>();
    }

};

struct HopsDecoder : GroupDecoder
{
private:
    NestedGroupDecoder m_nestedGroup;

public:
    explicit HopsDecoder(FieldDecoder& decoder) : 
        GroupDecoder{decoder},
        m_nestedGroup{decoder}
    {
    }

    HopsDecoder(const HopsDecoder&) = delete;
    HopsDecoder& operator=(const HopsDecoder&) = delete;
    HopsDecoder(HopsDecoder&&) = delete;
    HopsDecoder& operator=(HopsDecoder&&) = delete;

    HopsDecoder& wrap()
    {
        GroupDecoder::wrap<627>();
        return *this;
    }

    HopsDecoder& next()
    {
        GroupDecoder::next();
        return *this;
    }

    [[nodiscard]] std::expected<std::string_view, Result> hopCompID() const
    {
        return m_decoder.getString<628, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> hopSendingTime() const
    {
        return m_decoder.getTimestamp<629, false, RecordType::Group>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> hopRefID() const
    {
        return m_decoder.getUint32<630, false, RecordType::Group>();
    }

    [[nodiscard]] NestedGroupDecoder& nestedGroup()
    {
        return m_nestedGroup.wrap();
    }

};

struct LogonDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    DataDecoder m_xmlData;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_encryptMethodIndex{-1};
    int8_t m_heartbeatIntervalIndex{-1};

public:
    LogonDecoder() : 
        m_hops{m_decoder},
        m_xmlData{m_decoder}
    {
    }

    LogonDecoder(const SessionContext* context, const TokenizedMessage& message)
        : LogonDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    LogonDecoder(const LogonDecoder&) = delete;
    LogonDecoder& operator=(const LogonDecoder&) = delete;
    LogonDecoder(LogonDecoder&&) = delete;
    LogonDecoder& operator=(LogonDecoder&&) = delete;

    static constexpr uint16_t MessageId = 'A';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_heartbeatIntervalIndex = static_cast<int8_t>(m_decoder.findIndex<108, RecordType::Message>());
        if (m_heartbeatIntervalIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_encryptMethodIndex = static_cast<int8_t>(m_decoder.findIndex<98, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<Encryption::Values, Result> encryptMethod() const
    {
        if (m_encryptMethodIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.enumAt<Encryption>(m_encryptMethodIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> heartbeatInterval() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_heartbeatIntervalIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

    [[nodiscard]] DataDecoder& xmlData()
    {
        return m_xmlData.wrap<212, 213>();
    }

};

struct LogoutDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_textIndex{-1};

public:
    LogoutDecoder() : 
        m_hops{m_decoder}
    {
    }

    LogoutDecoder(const SessionContext* context, const TokenizedMessage& message)
        : LogoutDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    LogoutDecoder(const LogoutDecoder&) = delete;
    LogoutDecoder& operator=(const LogoutDecoder&) = delete;
    LogoutDecoder(LogoutDecoder&&) = delete;
    LogoutDecoder& operator=(LogoutDecoder&&) = delete;

    static constexpr uint16_t MessageId = '5';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_textIndex = static_cast<int8_t>(m_decoder.findIndex<58, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> text() const
    {
        if (m_textIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_textIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct HeartbeatDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_testReqIDIndex{-1};

public:
    HeartbeatDecoder() : 
        m_hops{m_decoder}
    {
    }

    HeartbeatDecoder(const SessionContext* context, const TokenizedMessage& message)
        : HeartbeatDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    HeartbeatDecoder(const HeartbeatDecoder&) = delete;
    HeartbeatDecoder& operator=(const HeartbeatDecoder&) = delete;
    HeartbeatDecoder(HeartbeatDecoder&&) = delete;
    HeartbeatDecoder& operator=(HeartbeatDecoder&&) = delete;

    static constexpr uint16_t MessageId = '0';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_testReqIDIndex = static_cast<int8_t>(m_decoder.findIndex<112, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> testReqID() const
    {
        if (m_testReqIDIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_testReqIDIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct TestRequestDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_testReqIDIndex{-1};

public:
    TestRequestDecoder() : 
        m_hops{m_decoder}
    {
    }

    TestRequestDecoder(const SessionContext* context, const TokenizedMessage& message)
        : TestRequestDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    TestRequestDecoder(const TestRequestDecoder&) = delete;
    TestRequestDecoder& operator=(const TestRequestDecoder&) = delete;
    TestRequestDecoder(TestRequestDecoder&&) = delete;
    TestRequestDecoder& operator=(TestRequestDecoder&&) = delete;

    static constexpr uint16_t MessageId = '1';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_testReqIDIndex = static_cast<int8_t>(m_decoder.findIndex<112, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> testReqID() const
    {
        if (m_testReqIDIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_testReqIDIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct ResendRequestDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_beginSeqNoIndex{-1};
    int8_t m_endSeqNoIndex{-1};

public:
    ResendRequestDecoder() : 
        m_hops{m_decoder}
    {
    }

    ResendRequestDecoder(const SessionContext* context, const TokenizedMessage& message)
        : ResendRequestDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    ResendRequestDecoder(const ResendRequestDecoder&) = delete;
    ResendRequestDecoder& operator=(const ResendRequestDecoder&) = delete;
    ResendRequestDecoder(ResendRequestDecoder&&) = delete;
    ResendRequestDecoder& operator=(ResendRequestDecoder&&) = delete;

    static constexpr uint16_t MessageId = '2';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_beginSeqNoIndex = static_cast<int8_t>(m_decoder.findIndex<7, RecordType::Message>());
        if (m_beginSeqNoIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_endSeqNoIndex = static_cast<int8_t>(m_decoder.findIndex<16, RecordType::Message>());
        if (m_endSeqNoIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> beginSeqNo() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_beginSeqNoIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> endSeqNo() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_endSeqNoIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct RejectDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_refSeqNumIndex{-1};
    int8_t m_refTagIDIndex{-1};
    int8_t m_refMsgTypeIndex{-1};
    int8_t m_sessionRejectReasonIndex{-1};
    int8_t m_textIndex{-1};

public:
    RejectDecoder() : 
        m_hops{m_decoder}
    {
    }

    RejectDecoder(const SessionContext* context, const TokenizedMessage& message)
        : RejectDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    RejectDecoder(const RejectDecoder&) = delete;
    RejectDecoder& operator=(const RejectDecoder&) = delete;
    RejectDecoder(RejectDecoder&&) = delete;
    RejectDecoder& operator=(RejectDecoder&&) = delete;

    static constexpr uint16_t MessageId = '3';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_refSeqNumIndex = static_cast<int8_t>(m_decoder.findIndex<45, RecordType::Message>());
        if (m_refSeqNumIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_refTagIDIndex = static_cast<int8_t>(m_decoder.findIndex<371, RecordType::Message>());
        m_refMsgTypeIndex = static_cast<int8_t>(m_decoder.findIndex<372, RecordType::Message>());
        m_sessionRejectReasonIndex = static_cast<int8_t>(m_decoder.findIndex<373, RecordType::Message>());
        m_textIndex = static_cast<int8_t>(m_decoder.findIndex<58, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> refSeqNum() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_refSeqNumIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> refTagID() const
    {
        if (m_refTagIDIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::uint32_t>(m_refTagIDIndex);
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> refMsgType() const
    {
        if (m_refMsgTypeIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.enumAt<MessageType>(m_refMsgTypeIndex);
    }

    [[nodiscard]] std::expected<SessionRejectReason::Values, Result> sessionRejectReason() const
    {
        if (m_sessionRejectReasonIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.enumAt<SessionRejectReason>(m_sessionRejectReasonIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> text() const
    {
        if (m_textIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_textIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct SequenceResetDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_gapFillFlagIndex{-1};
    int8_t m_newSeqNoIndex{-1};

public:
    SequenceResetDecoder() : 
        m_hops{m_decoder}
    {
    }

    SequenceResetDecoder(const SessionContext* context, const TokenizedMessage& message)
        : SequenceResetDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    SequenceResetDecoder(const SequenceResetDecoder&) = delete;
    SequenceResetDecoder& operator=(const SequenceResetDecoder&) = delete;
    SequenceResetDecoder(SequenceResetDecoder&&) = delete;
    SequenceResetDecoder& operator=(SequenceResetDecoder&&) = delete;

    static constexpr uint16_t MessageId = '4';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_newSeqNoIndex = static_cast<int8_t>(m_decoder.findIndex<36, RecordType::Message>());
        if (m_newSeqNoIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_gapFillFlagIndex = static_cast<int8_t>(m_decoder.findIndex<123, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<GapFillFlag::Values, Result> gapFillFlag() const
    {
        if (m_gapFillFlagIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.enumAt<GapFillFlag>(m_gapFillFlagIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> newSeqNo() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_newSeqNoIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct ExecutionReportDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_orderIDIndex{-1};
    int8_t m_clOrdIDIndex{-1};
    int8_t m_execIDIndex{-1};
    int8_t m_execTypeIndex{-1};
    int8_t m_ordStatusIndex{-1};
    int8_t m_symbolIndex{-1};
    int8_t m_sideIndex{-1};
    int8_t m_orderQtyIndex{-1};
    int8_t m_priceIndex{-1};
    int8_t m_lastQtyIndex{-1};
    int8_t m_lastPxIndex{-1};
    int8_t m_leavesQtyIndex{-1};
    int8_t m_cumQtyIndex{-1};
    int8_t m_avgPxIndex{-1};
    int8_t m_transactTimeIndex{-1};
    int8_t m_textIndex{-1};

public:
    ExecutionReportDecoder() : 
        m_hops{m_decoder}
    {
    }

    ExecutionReportDecoder(const SessionContext* context, const TokenizedMessage& message)
        : ExecutionReportDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    ExecutionReportDecoder(const ExecutionReportDecoder&) = delete;
    ExecutionReportDecoder& operator=(const ExecutionReportDecoder&) = delete;
    ExecutionReportDecoder(ExecutionReportDecoder&&) = delete;
    ExecutionReportDecoder& operator=(ExecutionReportDecoder&&) = delete;

    static constexpr uint16_t MessageId = '8';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_orderIDIndex = static_cast<int8_t>(m_decoder.findIndex<37, RecordType::Message>());
        if (m_orderIDIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_execIDIndex = static_cast<int8_t>(m_decoder.findIndex<17, RecordType::Message>());
        if (m_execIDIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_execTypeIndex = static_cast<int8_t>(m_decoder.findIndex<150, RecordType::Message>());
        if (m_execTypeIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_ordStatusIndex = static_cast<int8_t>(m_decoder.findIndex<39, RecordType::Message>());
        if (m_ordStatusIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_symbolIndex = static_cast<int8_t>(m_decoder.findIndex<55, RecordType::Message>());
        if (m_symbolIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_sideIndex = static_cast<int8_t>(m_decoder.findIndex<54, RecordType::Message>());
        if (m_sideIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_leavesQtyIndex = static_cast<int8_t>(m_decoder.findIndex<151, RecordType::Message>());
        if (m_leavesQtyIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_cumQtyIndex = static_cast<int8_t>(m_decoder.findIndex<14, RecordType::Message>());
        if (m_cumQtyIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_avgPxIndex = static_cast<int8_t>(m_decoder.findIndex<6, RecordType::Message>());
        if (m_avgPxIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_transactTimeIndex = static_cast<int8_t>(m_decoder.findIndex<60, RecordType::Message>());
        if (m_transactTimeIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_clOrdIDIndex = static_cast<int8_t>(m_decoder.findIndex<11, RecordType::Message>());
        m_orderQtyIndex = static_cast<int8_t>(m_decoder.findIndex<38, RecordType::Message>());
        m_priceIndex = static_cast<int8_t>(m_decoder.findIndex<44, RecordType::Message>());
        m_lastQtyIndex = static_cast<int8_t>(m_decoder.findIndex<32, RecordType::Message>());
        m_lastPxIndex = static_cast<int8_t>(m_decoder.findIndex<31, RecordType::Message>());
        m_textIndex = static_cast<int8_t>(m_decoder.findIndex<58, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> orderID() const
    {
        return m_decoder.valueAt<std::string_view>(m_orderIDIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> clOrdID() const
    {
        if (m_clOrdIDIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_clOrdIDIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> execID() const
    {
        return m_decoder.valueAt<std::string_view>(m_execIDIndex);
    }

    [[nodiscard]] std::expected<ExecType::Values, Result> execType() const
    {
        return m_decoder.enumAt<ExecType>(m_execTypeIndex);
    }

    [[nodiscard]] std::expected<OrdStatus::Values, Result> ordStatus() const
    {
        return m_decoder.enumAt<OrdStatus>(m_ordStatusIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> symbol() const
    {
        return m_decoder.valueAt<std::string_view>(m_symbolIndex);
    }

    [[nodiscard]] std::expected<Side::Values, Result> side() const
    {
        return m_decoder.enumAt<Side>(m_sideIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> orderQty() const
    {
        if (m_orderQtyIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::uint32_t>(m_orderQtyIndex);
    }

    [[nodiscard]] std::expected<utils::FixedDecimal, Result> price() const
    {
        if (m_priceIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<utils::FixedDecimal>(m_priceIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> lastQty() const
    {
        if (m_lastQtyIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::uint32_t>(m_lastQtyIndex);
    }

    [[nodiscard]] std::expected<utils::FixedDecimal, Result> lastPx() const
    {
        if (m_lastPxIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<utils::FixedDecimal>(m_lastPxIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> leavesQty() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_leavesQtyIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> cumQty() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_cumQtyIndex);
    }

    [[nodiscard]] std::expected<utils::FixedDecimal, Result> avgPx() const
    {
        return m_decoder.valueAt<utils::FixedDecimal>(m_avgPxIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> transactTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_transactTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> text() const
    {
        if (m_textIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_textIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

struct NewOrderSingleDecoder : MessageDecoder
{
private:
    HopsDecoder m_hops;

    int8_t m_senderIndex{-1};
    int8_t m_targetIndex{-1};
    int8_t m_sequenceNumberIndex{-1};
    int8_t m_sendingTimeIndex{-1};
    int8_t m_accountIndex{-1};
    int8_t m_clOrdIDIndex{-1};
    int8_t m_handlInstIndex{-1};
    int8_t m_symbolIndex{-1};
    int8_t m_sideIndex{-1};
    int8_t m_transactTimeIndex{-1};
    int8_t m_orderQtyIndex{-1};
    int8_t m_ordTypeIndex{-1};
    int8_t m_priceIndex{-1};
    int8_t m_timeInForceIndex{-1};
    int8_t m_textIndex{-1};
    int8_t m_tradeDateIndex{-1};
    int8_t m_maturityTimeIndex{-1};

public:
    NewOrderSingleDecoder() : 
        m_hops{m_decoder}
    {
    }

    NewOrderSingleDecoder(const SessionContext* context, const TokenizedMessage& message)
        : NewOrderSingleDecoder{}
    {
        MessageDecoder::wrap(message);
        MessageDecoder::context(context);
    }

    NewOrderSingleDecoder(const NewOrderSingleDecoder&) = delete;
    NewOrderSingleDecoder& operator=(const NewOrderSingleDecoder&) = delete;
    NewOrderSingleDecoder(NewOrderSingleDecoder&&) = delete;
    NewOrderSingleDecoder& operator=(NewOrderSingleDecoder&&) = delete;

    static constexpr uint16_t MessageId = 'D';

    [[nodiscard]] Result validate()
    {
        m_senderIndex = static_cast<int8_t>(m_decoder.findIndex<49, RecordType::Message>());
        if (m_senderIndex < 0)
        {
            return Result::InvalidSenderCompId;
        }
        m_targetIndex = static_cast<int8_t>(m_decoder.findIndex<56, RecordType::Message>());
        if (m_targetIndex < 0)
        {
            return Result::InvalidTargetCompId;
        }
        m_sequenceNumberIndex = static_cast<int8_t>(m_decoder.findIndex<34, RecordType::Message>());
        if (m_sequenceNumberIndex < 0)
        {
            return Result::InvalidSequenceNumber;
        }
        m_sendingTimeIndex = static_cast<int8_t>(m_decoder.findIndex<52, RecordType::Message>());
        if (m_sendingTimeIndex < 0)
        {
            return Result::InvalidSendingTime;
        }
        m_clOrdIDIndex = static_cast<int8_t>(m_decoder.findIndex<11, RecordType::Message>());
        if (m_clOrdIDIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_handlInstIndex = static_cast<int8_t>(m_decoder.findIndex<21, RecordType::Message>());
        if (m_handlInstIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_symbolIndex = static_cast<int8_t>(m_decoder.findIndex<55, RecordType::Message>());
        if (m_symbolIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_sideIndex = static_cast<int8_t>(m_decoder.findIndex<54, RecordType::Message>());
        if (m_sideIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_transactTimeIndex = static_cast<int8_t>(m_decoder.findIndex<60, RecordType::Message>());
        if (m_transactTimeIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_orderQtyIndex = static_cast<int8_t>(m_decoder.findIndex<38, RecordType::Message>());
        if (m_orderQtyIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_ordTypeIndex = static_cast<int8_t>(m_decoder.findIndex<40, RecordType::Message>());
        if (m_ordTypeIndex < 0)
        {
            return Result::RequiredFieldMissing;
        }
        m_accountIndex = static_cast<int8_t>(m_decoder.findIndex<1, RecordType::Message>());
        m_priceIndex = static_cast<int8_t>(m_decoder.findIndex<44, RecordType::Message>());
        m_timeInForceIndex = static_cast<int8_t>(m_decoder.findIndex<59, RecordType::Message>());
        m_textIndex = static_cast<int8_t>(m_decoder.findIndex<58, RecordType::Message>());
        m_tradeDateIndex = static_cast<int8_t>(m_decoder.findIndex<75, RecordType::Message>());
        m_maturityTimeIndex = static_cast<int8_t>(m_decoder.findIndex<1079, RecordType::Message>());
        return validateSession();
    }

    [[nodiscard]] std::expected<Protocol::Values, Result> beginString() const
    {
        return m_decoder.getEnum<8, true, Protocol, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> bodyLength() const
    {
        return m_decoder.getUint32<9, true, RecordType::Message>();
    }

    [[nodiscard]] std::expected<MessageType::Values, Result> msgType() const
    {
        return m_decoder.getEnum<35, true, MessageType, RecordType::Message>();
    }

    [[nodiscard]] std::expected<std::string_view, Result> sender() const
    {
        return m_decoder.valueAt<std::string_view>(m_senderIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> target() const
    {
        return m_decoder.valueAt<std::string_view>(m_targetIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> sequenceNumber() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_sequenceNumberIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> sendingTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_sendingTimeIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> account() const
    {
        if (m_accountIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_accountIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> clOrdID() const
    {
        return m_decoder.valueAt<std::string_view>(m_clOrdIDIndex);
    }

    [[nodiscard]] std::expected<HandlInst::Values, Result> handlInst() const
    {
        return m_decoder.enumAt<HandlInst>(m_handlInstIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> symbol() const
    {
        return m_decoder.valueAt<std::string_view>(m_symbolIndex);
    }

    [[nodiscard]] std::expected<Side::Values, Result> side() const
    {
        return m_decoder.enumAt<Side>(m_sideIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> transactTime() const
    {
        return m_decoder.valueAt<std::chrono::milliseconds>(m_transactTimeIndex);
    }

    [[nodiscard]] std::expected<std::uint32_t, Result> orderQty() const
    {
        return m_decoder.valueAt<std::uint32_t>(m_orderQtyIndex);
    }

    [[nodiscard]] std::expected<OrdType::Values, Result> ordType() const
    {
        return m_decoder.enumAt<OrdType>(m_ordTypeIndex);
    }

    [[nodiscard]] std::expected<utils::FixedDecimal, Result> price() const
    {
        if (m_priceIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<utils::FixedDecimal>(m_priceIndex);
    }

    [[nodiscard]] std::expected<TimeInForce::Values, Result> timeInForce() const
    {
        if (m_timeInForceIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.enumAt<TimeInForce>(m_timeInForceIndex);
    }

    [[nodiscard]] std::expected<std::string_view, Result> text() const
    {
        if (m_textIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.valueAt<std::string_view>(m_textIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> tradeDate() const
    {
        if (m_tradeDateIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.dateOnlyAt(m_tradeDateIndex);
    }

    [[nodiscard]] std::expected<std::chrono::milliseconds, Result> maturityTime() const
    {
        if (m_maturityTimeIndex < 0)
        {
            return std::unexpected{Result::Success};
        }
        return m_decoder.timeOnlyAt(m_maturityTimeIndex);
    }

    [[nodiscard]] HopsDecoder& hops()
    {
        return m_hops.wrap();
    }

};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_MESSAGE_DECODERS_HPP
