// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_ENCODERS_HPP
#define SIMD_FIX_MESSAGE_ENCODERS_HPP

#include "org/limitless/fix/encoder/GroupEncoder.hpp"
#include "org/limitless/fix/encoder/MessageEncoder.hpp"
#include "org/limitless/fix/messages/FixTypes.hpp"

namespace org::limitless::fix::messages {

using namespace org::limitless::fix::encoder;

struct NestedGroupEncoder : GroupEncoder
{
    explicit NestedGroupEncoder(FieldEncoder& encoder) : 
        GroupEncoder{encoder}
    {
    }

    NestedGroupEncoder(const NestedGroupEncoder&) = delete;
    NestedGroupEncoder& operator=(const NestedGroupEncoder&) = delete;
    NestedGroupEncoder(NestedGroupEncoder&&) = delete;
    NestedGroupEncoder& operator=(NestedGroupEncoder&&) = delete;

    NestedGroupEncoder& wrap(const uint32_t count)
    {
        GroupEncoder::wrap(500, count);
        return *this;
    }

    NestedGroupEncoder& next()
    {
        GroupEncoder::next();
        return *this;
    }

    NestedGroupEncoder& name(const std::string_view value)
    {
        m_encoder.encode<501, false, ParentType::Group>(value);
        return *this;
    }

    NestedGroupEncoder& nestedOne(const std::uint32_t value)
    {
        m_encoder.encode<601, false, ParentType::Group>(value);
        return *this;
    }

    NestedGroupEncoder& nestedTwo(const std::uint32_t value)
    {
        m_encoder.encode<602, false, ParentType::Group>(value);
        return *this;
    }

};

struct HopsEncoder : GroupEncoder
{
private:
    NestedGroupEncoder m_nestedGroup;

public:
    explicit HopsEncoder(FieldEncoder& encoder) : 
        GroupEncoder{encoder},
        m_nestedGroup{encoder}
    {
    }

    HopsEncoder(const HopsEncoder&) = delete;
    HopsEncoder& operator=(const HopsEncoder&) = delete;
    HopsEncoder(HopsEncoder&&) = delete;
    HopsEncoder& operator=(HopsEncoder&&) = delete;

    HopsEncoder& wrap(const uint32_t count)
    {
        GroupEncoder::wrap(627, count);
        return *this;
    }

    HopsEncoder& next()
    {
        GroupEncoder::next();
        return *this;
    }

    HopsEncoder& hopCompID(const std::string_view value)
    {
        m_encoder.encode<628, false, ParentType::Group>(value);
        return *this;
    }

    HopsEncoder& hopSendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<629, false, ParentType::Group>(value);
        return *this;
    }

    HopsEncoder& hopRefID(const std::uint32_t value)
    {
        m_encoder.encode<630, false, ParentType::Group>(value);
        return *this;
    }

    NestedGroupEncoder& nestedGroup(const uint32_t count)
    {
        return m_nestedGroup.wrap(count);
    }

};

struct LogonEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    LogonEncoder() : 
        m_hops{m_encoder}
    {
    }

    LogonEncoder(const LogonEncoder&) = delete;
    LogonEncoder& operator=(const LogonEncoder&) = delete;
    LogonEncoder(LogonEncoder&&) = delete;
    LogonEncoder& operator=(LogonEncoder&&) = delete;

    static constexpr uint16_t MessageId = 'A';

    LogonEncoder& wrap(const std::span<uint8_t> data)
    {
        MessageEncoder::wrap(data);
        return *this;
    }

    LogonEncoder& bodyLength(const std::uint32_t value)
    {
        m_encoder.encode<9, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& msgType(const MessageType::Values value)
    {
        m_encoder.encode<35, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& sender(const std::string_view value)
    {
        m_encoder.encode<49, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& target(const std::string_view value)
    {
        m_encoder.encode<56, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<34, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<52, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& encryptMethod(const Encryption::Values value)
    {
        m_encoder.encode<98, false, ParentType::Message>(value);
        return *this;
    }

    LogonEncoder& heartbeatInterval(const std::uint32_t value)
    {
        m_encoder.encode<108, false, ParentType::Message>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct LogoutEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    LogoutEncoder() : 
        m_hops{m_encoder}
    {
    }

    LogoutEncoder(const LogoutEncoder&) = delete;
    LogoutEncoder& operator=(const LogoutEncoder&) = delete;
    LogoutEncoder(LogoutEncoder&&) = delete;
    LogoutEncoder& operator=(LogoutEncoder&&) = delete;

    static constexpr uint16_t MessageId = '5';

    LogoutEncoder& wrap(const std::span<uint8_t> data)
    {
        MessageEncoder::wrap(data);
        return *this;
    }

    LogoutEncoder& bodyLength(const std::uint32_t value)
    {
        m_encoder.encode<9, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& msgType(const MessageType::Values value)
    {
        m_encoder.encode<35, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& sender(const std::string_view value)
    {
        m_encoder.encode<49, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& target(const std::string_view value)
    {
        m_encoder.encode<56, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<34, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<52, false, ParentType::Message>(value);
        return *this;
    }

    LogoutEncoder& text(const std::string_view value)
    {
        m_encoder.encode<58, false, ParentType::Message>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct HeartbeatEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    HeartbeatEncoder() : 
        m_hops{m_encoder}
    {
    }

    HeartbeatEncoder(const HeartbeatEncoder&) = delete;
    HeartbeatEncoder& operator=(const HeartbeatEncoder&) = delete;
    HeartbeatEncoder(HeartbeatEncoder&&) = delete;
    HeartbeatEncoder& operator=(HeartbeatEncoder&&) = delete;

    static constexpr uint16_t MessageId = '0';

    HeartbeatEncoder& wrap(const std::span<uint8_t> data)
    {
        MessageEncoder::wrap(data);
        return *this;
    }

    HeartbeatEncoder& bodyLength(const std::uint32_t value)
    {
        m_encoder.encode<9, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& msgType(const MessageType::Values value)
    {
        m_encoder.encode<35, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& sender(const std::string_view value)
    {
        m_encoder.encode<49, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& target(const std::string_view value)
    {
        m_encoder.encode<56, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<34, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<52, false, ParentType::Message>(value);
        return *this;
    }

    HeartbeatEncoder& testReqID(const std::string_view value)
    {
        m_encoder.encode<112, false, ParentType::Message>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct TestRequestEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    TestRequestEncoder() : 
        m_hops{m_encoder}
    {
    }

    TestRequestEncoder(const TestRequestEncoder&) = delete;
    TestRequestEncoder& operator=(const TestRequestEncoder&) = delete;
    TestRequestEncoder(TestRequestEncoder&&) = delete;
    TestRequestEncoder& operator=(TestRequestEncoder&&) = delete;

    static constexpr uint16_t MessageId = '1';

    TestRequestEncoder& wrap(const std::span<uint8_t> data)
    {
        MessageEncoder::wrap(data);
        return *this;
    }

    TestRequestEncoder& bodyLength(const std::uint32_t value)
    {
        m_encoder.encode<9, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& msgType(const MessageType::Values value)
    {
        m_encoder.encode<35, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& sender(const std::string_view value)
    {
        m_encoder.encode<49, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& target(const std::string_view value)
    {
        m_encoder.encode<56, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<34, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<52, false, ParentType::Message>(value);
        return *this;
    }

    TestRequestEncoder& testReqID(const std::string_view value)
    {
        m_encoder.encode<112, false, ParentType::Message>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

} // namespace org::limitless::fix::encoder

#endif //SIMD_FIX_MESSAGE_ENCODERS_HPP
