// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_ENCODERS_HPP
#define SIMD_FIX_MESSAGE_ENCODERS_HPP

#include "org/limitless/fix/encoder/DataEncoder.hpp"
#include "org/limitless/fix/encoder/GroupEncoder.hpp"
#include "org/limitless/fix/encoder/MessageEncoder.hpp"
#include "org/limitless/fix/encoder/PayloadEncoder.hpp"
#include "org/limitless/fix/messages/FixTypes.hpp"

namespace org::limitless::fix::messages {

using namespace org::limitless::fix::encoder;

struct NestedGroupEncoder : GroupEncoder
{
    explicit NestedGroupEncoder(FieldEncoder& encoder) : 
        GroupEncoder{encoder}
    {
    }

    NestedGroupEncoder(const NestedGroupEncoder&) = delete;
    NestedGroupEncoder& operator=(const NestedGroupEncoder&) = delete;
    NestedGroupEncoder(NestedGroupEncoder&&) = delete;
    NestedGroupEncoder& operator=(NestedGroupEncoder&&) = delete;

    NestedGroupEncoder& wrap(const uint32_t count)
    {
        GroupEncoder::wrap(500, count);
        return *this;
    }

    NestedGroupEncoder& next()
    {
        GroupEncoder::next();
        return *this;
    }

    NestedGroupEncoder& name(const std::string_view value)
    {
        m_encoder.encode<"501", std::string_view>(value);
        return *this;
    }

    NestedGroupEncoder& nestedOne(const std::uint32_t value)
    {
        m_encoder.encode<"601", std::uint32_t>(value);
        return *this;
    }

    NestedGroupEncoder& nestedTwo(const std::uint32_t value)
    {
        m_encoder.encode<"602", std::uint32_t>(value);
        return *this;
    }

};

struct HopsEncoder : GroupEncoder
{
private:
    NestedGroupEncoder m_nestedGroup;

public:
    explicit HopsEncoder(FieldEncoder& encoder) : 
        GroupEncoder{encoder},
        m_nestedGroup{encoder}
    {
    }

    HopsEncoder(const HopsEncoder&) = delete;
    HopsEncoder& operator=(const HopsEncoder&) = delete;
    HopsEncoder(HopsEncoder&&) = delete;
    HopsEncoder& operator=(HopsEncoder&&) = delete;

    HopsEncoder& wrap(const uint32_t count)
    {
        GroupEncoder::wrap(627, count);
        return *this;
    }

    HopsEncoder& next()
    {
        GroupEncoder::next();
        return *this;
    }

    HopsEncoder& hopCompID(const std::string_view value)
    {
        m_encoder.encode<"628", std::string_view>(value);
        return *this;
    }

    HopsEncoder& hopSendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"629", std::chrono::milliseconds>(value);
        return *this;
    }

    HopsEncoder& hopRefID(const std::uint32_t value)
    {
        m_encoder.encode<"630", std::uint32_t>(value);
        return *this;
    }

    NestedGroupEncoder& nestedGroup(const uint32_t count)
    {
        return m_nestedGroup.wrap(count);
    }

};

struct LogonEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

    DataEncoder m_xmlData;

public:
    LogonEncoder() : 
        m_hops{m_encoder},
        m_xmlData{m_encoder}
    {
    }

    LogonEncoder(const LogonEncoder&) = delete;
    LogonEncoder& operator=(const LogonEncoder&) = delete;
    LogonEncoder(LogonEncoder&&) = delete;
    LogonEncoder& operator=(LogonEncoder&&) = delete;

    static constexpr std::string_view MessageId = "A";

    LogonEncoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)
    {
        MessageEncoder::wrap(data, offset);
        return *this;
    }

    [[nodiscard]] std::string_view type() const
    {
        return MessageId;
    }

    LogonEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<"34", std::uint32_t>(value);
        return *this;
    }

    LogonEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"52", std::chrono::milliseconds>(value);
        return *this;
    }

    LogonEncoder& encryptMethod(const Encryption::Values value)
    {
        m_encoder.encode<"98", false, Encryption>(value);
        return *this;
    }

    LogonEncoder& heartbeatInterval(const std::uint32_t value)
    {
        m_encoder.encode<"108", std::uint32_t>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

    LogonEncoder& xmlData(const std::span<const uint8_t> data)
    {
        m_xmlData.encode<"212", "213">(data);
        return *this;
    }

};

struct LogoutEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    LogoutEncoder() : 
        m_hops{m_encoder}
    {
    }

    LogoutEncoder(const LogoutEncoder&) = delete;
    LogoutEncoder& operator=(const LogoutEncoder&) = delete;
    LogoutEncoder(LogoutEncoder&&) = delete;
    LogoutEncoder& operator=(LogoutEncoder&&) = delete;

    static constexpr std::string_view MessageId = "5";

    LogoutEncoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)
    {
        MessageEncoder::wrap(data, offset);
        return *this;
    }

    [[nodiscard]] std::string_view type() const
    {
        return MessageId;
    }

    LogoutEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<"34", std::uint32_t>(value);
        return *this;
    }

    LogoutEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"52", std::chrono::milliseconds>(value);
        return *this;
    }

    LogoutEncoder& text(const std::string_view value)
    {
        m_encoder.encode<"58", std::string_view>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct HeartbeatEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    HeartbeatEncoder() : 
        m_hops{m_encoder}
    {
    }

    HeartbeatEncoder(const HeartbeatEncoder&) = delete;
    HeartbeatEncoder& operator=(const HeartbeatEncoder&) = delete;
    HeartbeatEncoder(HeartbeatEncoder&&) = delete;
    HeartbeatEncoder& operator=(HeartbeatEncoder&&) = delete;

    static constexpr std::string_view MessageId = "0";

    HeartbeatEncoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)
    {
        MessageEncoder::wrap(data, offset);
        return *this;
    }

    [[nodiscard]] std::string_view type() const
    {
        return MessageId;
    }

    HeartbeatEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<"34", std::uint32_t>(value);
        return *this;
    }

    HeartbeatEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"52", std::chrono::milliseconds>(value);
        return *this;
    }

    HeartbeatEncoder& testReqID(const std::string_view value)
    {
        m_encoder.encode<"112", std::string_view>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct TestRequestEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    TestRequestEncoder() : 
        m_hops{m_encoder}
    {
    }

    TestRequestEncoder(const TestRequestEncoder&) = delete;
    TestRequestEncoder& operator=(const TestRequestEncoder&) = delete;
    TestRequestEncoder(TestRequestEncoder&&) = delete;
    TestRequestEncoder& operator=(TestRequestEncoder&&) = delete;

    static constexpr std::string_view MessageId = "1";

    TestRequestEncoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)
    {
        MessageEncoder::wrap(data, offset);
        return *this;
    }

    [[nodiscard]] std::string_view type() const
    {
        return MessageId;
    }

    TestRequestEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<"34", std::uint32_t>(value);
        return *this;
    }

    TestRequestEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"52", std::chrono::milliseconds>(value);
        return *this;
    }

    TestRequestEncoder& testReqID(const std::string_view value)
    {
        m_encoder.encode<"112", std::string_view>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

struct NewOrderSingleEncoder : MessageEncoder
{
private:
    HopsEncoder m_hops;

public:
    NewOrderSingleEncoder() : 
        m_hops{m_encoder}
    {
    }

    NewOrderSingleEncoder(const NewOrderSingleEncoder&) = delete;
    NewOrderSingleEncoder& operator=(const NewOrderSingleEncoder&) = delete;
    NewOrderSingleEncoder(NewOrderSingleEncoder&&) = delete;
    NewOrderSingleEncoder& operator=(NewOrderSingleEncoder&&) = delete;

    static constexpr std::string_view MessageId = "D";

    NewOrderSingleEncoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)
    {
        MessageEncoder::wrap(data, offset);
        return *this;
    }

    [[nodiscard]] std::string_view type() const
    {
        return MessageId;
    }

    NewOrderSingleEncoder& sequenceNumber(const std::uint32_t value)
    {
        m_encoder.encode<"34", std::uint32_t>(value);
        return *this;
    }

    NewOrderSingleEncoder& sendingTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"52", std::chrono::milliseconds>(value);
        return *this;
    }

    NewOrderSingleEncoder& account(const std::string_view value)
    {
        m_encoder.encode<"1", std::string_view>(value);
        return *this;
    }

    NewOrderSingleEncoder& clOrdID(const std::string_view value)
    {
        m_encoder.encode<"11", std::string_view>(value);
        return *this;
    }

    NewOrderSingleEncoder& handlInst(const HandlInst::Values value)
    {
        m_encoder.encode<"21", true, HandlInst>(value);
        return *this;
    }

    NewOrderSingleEncoder& symbol(const std::string_view value)
    {
        m_encoder.encode<"55", std::string_view>(value);
        return *this;
    }

    NewOrderSingleEncoder& side(const Side::Values value)
    {
        m_encoder.encode<"54", true, Side>(value);
        return *this;
    }

    NewOrderSingleEncoder& transactTime(const std::chrono::milliseconds value)
    {
        m_encoder.encode<"60", std::chrono::milliseconds>(value);
        return *this;
    }

    NewOrderSingleEncoder& orderQty(const std::uint32_t value)
    {
        m_encoder.encode<"38", std::uint32_t>(value);
        return *this;
    }

    NewOrderSingleEncoder& ordType(const OrdType::Values value)
    {
        m_encoder.encode<"40", true, OrdType>(value);
        return *this;
    }

    NewOrderSingleEncoder& price(const utils::FixedDecimal value)
    {
        m_encoder.encode<"44">(value);
        return *this;
    }

    NewOrderSingleEncoder& timeInForce(const TimeInForce::Values value)
    {
        m_encoder.encode<"59", false, TimeInForce>(value);
        return *this;
    }

    NewOrderSingleEncoder& text(const std::string_view value)
    {
        m_encoder.encode<"58", std::string_view>(value);
        return *this;
    }

    HopsEncoder& hops(const uint32_t count)
    {
        return m_hops.wrap(count);
    }

};

template <FixedString Protocol, FixedString Target, FixedString Sender>
class FixPayloadEncoder
{
    PayloadEncoder<Protocol, Target, Sender> m_encoder;
public:
    FixPayloadEncoder() = default;

    FixPayloadEncoder& wrap(const uint32_t offset, const std::span<uint8_t> data)
    {
        m_encoder.wrap(offset, data);
        return *this;
    }

    [[nodiscard]] uint32_t offset() const
    {
        return m_encoder.offset();
    }

    template <typename MessageEncoderType>
    MessageEncoderType& wrapMessage(MessageEncoderType& message) const
    {
        return m_encoder.wrapMessage(message);
    }

    template <EncodableMessage Message>
    uint32_t encode(const Message& message)
    {
        return m_encoder.encode(message);
    }

    [[nodiscard]] uint32_t encodedLength() const
    {
        return m_encoder.encodedLength();
    }
};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_MESSAGE_ENCODERS_HPP
