// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_HANDLER_HPP
#define SIMD_FIX_MESSAGE_HANDLER_HPP

#include "org/limitless/fix/detail/Tokens.hpp"
#include "org/limitless/fix/messages/FixMessageDecoders.hpp"

namespace org::limitless::fix::messages {

using fix::Result;

template <typename Handler>
class MessageHandler
{
    const SessionContext* m_context{};

public:
    template <typename Event>
    Result::Values receive(Event&& event)
    {
        return static_cast<Handler*>(this)->handle(std::forward<Event>(event));
    }

    void setSessionContext(const SessionContext& context)
    {
        m_context = &context;
    }

    Result::Values handle(const detail::TokenizedMessage& message,
                          const uint8_t messageType)
    {
        auto status = Result::InvalidMessageType;
        switch (messageType)
        {
            case LogonDecoder::MessageId:
            {
                LogonDecoder logon{m_context, message};
                status = logon.validate();
                if (status == Result::Success)
                {
                    status = receive(logon);
                }
                break;
            }
            case LogoutDecoder::MessageId:
            {
                LogoutDecoder logout{m_context, message};
                status = logout.validate();
                if (status == Result::Success)
                {
                    status = receive(logout);
                }
                break;
            }
            case HeartbeatDecoder::MessageId:
            {
                HeartbeatDecoder heartbeat{m_context, message};
                status = heartbeat.validate();
                if (status == Result::Success)
                {
                    status = receive(heartbeat);
                }
                break;
            }
            case TestRequestDecoder::MessageId:
            {
                TestRequestDecoder testRequest{m_context, message};
                status = testRequest.validate();
                if (status == Result::Success)
                {
                    status = receive(testRequest);
                }
                break;
            }
            case ResendRequestDecoder::MessageId:
            {
                ResendRequestDecoder resendRequest{m_context, message};
                status = resendRequest.validate();
                if (status == Result::Success)
                {
                    status = receive(resendRequest);
                }
                break;
            }
            case RejectDecoder::MessageId:
            {
                RejectDecoder reject{m_context, message};
                status = reject.validate();
                if (status == Result::Success)
                {
                    status = receive(reject);
                }
                break;
            }
            case SequenceResetDecoder::MessageId:
            {
                SequenceResetDecoder sequenceReset{m_context, message};
                status = sequenceReset.validate();
                if (status == Result::Success)
                {
                    status = receive(sequenceReset);
                }
                break;
            }
            case ExecutionReportDecoder::MessageId:
            {
                ExecutionReportDecoder executionReport{m_context, message};
                status = executionReport.validate();
                if (status == Result::Success)
                {
                    status = receive(executionReport);
                }
                break;
            }
            case NewOrderSingleDecoder::MessageId:
            {
                NewOrderSingleDecoder newOrderSingle{m_context, message};
                status = newOrderSingle.validate();
                if (status == Result::Success)
                {
                    status = receive(newOrderSingle);
                }
                break;
            }
            default:
                break;
        }
        return status;
    }

protected:
    Result::Values handle(LogonDecoder&) { return Result::Success; }
    Result::Values handle(LogoutDecoder&) { return Result::Success; }
    Result::Values handle(HeartbeatDecoder&) { return Result::Success; }
    Result::Values handle(TestRequestDecoder&) { return Result::Success; }
    Result::Values handle(ResendRequestDecoder&) { return Result::Success; }
    Result::Values handle(RejectDecoder&) { return Result::Success; }
    Result::Values handle(SequenceResetDecoder&) { return Result::Success; }
    Result::Values handle(ExecutionReportDecoder&) { return Result::Success; }
    Result::Values handle(NewOrderSingleDecoder&) { return Result::Success; }
};

} // namespace org::limitless::fix::messages

#endif // SIMD_FIX_MESSAGE_HANDLER_HPP
