// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_MESSAGE_HANDLER_HPP
#define SIMD_FIX_MESSAGE_HANDLER_HPP

#include "org/limitless/fix/CodecTypes.hpp"
#include "org/limitless/fix/messages/FixMessageDecoders.hpp"

namespace org::limitless::fix::messages {

using fix::Result;

template <typename Handler>
class MessageHandler
{
    LogonDecoder m_logon;
    LogoutDecoder m_logout;
    HeartbeatDecoder m_heartbeat;
    TestRequestDecoder m_testRequest;
    ResendRequestDecoder m_resendRequest;
    RejectDecoder m_reject;
    SequenceResetDecoder m_sequenceReset;
    ExecutionReportDecoder m_executionReport;
    NewOrderSingleDecoder m_newOrderSingle;

public:
    template <typename Event>
    Result::Values receive(Event&& event)
    {
        return static_cast<Handler*>(this)->handle(std::forward<Event>(event));
    }

    void setSessionContext(const SessionContext& context)
    {
        m_logon.context(&context);
        m_logout.context(&context);
        m_heartbeat.context(&context);
        m_testRequest.context(&context);
        m_resendRequest.context(&context);
        m_reject.context(&context);
        m_sequenceReset.context(&context);
        m_executionReport.context(&context);
        m_newOrderSingle.context(&context);
    }

    Result::Values handle(const std::span<const uint8_t> data,
                          const std::span<Token> tokens,
                          const std::span<uint16_t> tags,
                          const int32_t count,
                          const uint8_t messageType)
    {
        auto status = Result::InvalidMessageType;
        switch (messageType)
        {
            case LogonDecoder::MessageId:
                m_logon.wrap(data, tokens, tags, count);
                status = m_logon.validate();
                if (status == Result::Success)
                {
                    status = receive(m_logon);
                }
                break;
            case LogoutDecoder::MessageId:
                m_logout.wrap(data, tokens, tags, count);
                status = m_logout.validate();
                if (status == Result::Success)
                {
                    status = receive(m_logout);
                }
                break;
            case HeartbeatDecoder::MessageId:
                m_heartbeat.wrap(data, tokens, tags, count);
                status = m_heartbeat.validate();
                if (status == Result::Success)
                {
                    status = receive(m_heartbeat);
                }
                break;
            case TestRequestDecoder::MessageId:
                m_testRequest.wrap(data, tokens, tags, count);
                status = m_testRequest.validate();
                if (status == Result::Success)
                {
                    status = receive(m_testRequest);
                }
                break;
            case ResendRequestDecoder::MessageId:
                m_resendRequest.wrap(data, tokens, tags, count);
                status = m_resendRequest.validate();
                if (status == Result::Success)
                {
                    status = receive(m_resendRequest);
                }
                break;
            case RejectDecoder::MessageId:
                m_reject.wrap(data, tokens, tags, count);
                status = m_reject.validate();
                if (status == Result::Success)
                {
                    status = receive(m_reject);
                }
                break;
            case SequenceResetDecoder::MessageId:
                m_sequenceReset.wrap(data, tokens, tags, count);
                status = m_sequenceReset.validate();
                if (status == Result::Success)
                {
                    status = receive(m_sequenceReset);
                }
                break;
            case ExecutionReportDecoder::MessageId:
                m_executionReport.wrap(data, tokens, tags, count);
                status = m_executionReport.validate();
                if (status == Result::Success)
                {
                    status = receive(m_executionReport);
                }
                break;
            case NewOrderSingleDecoder::MessageId:
                m_newOrderSingle.wrap(data, tokens, tags, count);
                status = m_newOrderSingle.validate();
                if (status == Result::Success)
                {
                    status = receive(m_newOrderSingle);
                }
                break;
            default:
                break;
        }
        return status;
    }

protected:
    Result::Values handle(LogonDecoder&) { return Result::Success; }
    Result::Values handle(LogoutDecoder&) { return Result::Success; }
    Result::Values handle(HeartbeatDecoder&) { return Result::Success; }
    Result::Values handle(TestRequestDecoder&) { return Result::Success; }
    Result::Values handle(ResendRequestDecoder&) { return Result::Success; }
    Result::Values handle(RejectDecoder&) { return Result::Success; }
    Result::Values handle(SequenceResetDecoder&) { return Result::Success; }
    Result::Values handle(ExecutionReportDecoder&) { return Result::Success; }
    Result::Values handle(NewOrderSingleDecoder&) { return Result::Success; }
};

} // namespace org::limitless::fix::messages

#endif // SIMD_FIX_MESSAGE_HANDLER_HPP
