// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_TYPES_HPP
#define SIMD_FIX_TYPES_HPP

#include <cstdint>

namespace org::limitless::fix::messages {

struct Encryption
{
    enum Values
    {
        Null,
        None
    };
    static constexpr std::string_view Codes[2]  =
    {
        "?",
        "0"
    };
};

struct MessageType
{
    enum Values
    {
        Null,
        Logon,
        Logout,
        TestRequest,
        Heartbeat
    };
    static constexpr std::string_view Codes[5]  =
    {
        "?",
        "A",
        "5",
        "1",
        "0"
    };
};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_TYPES_HPP
