// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_TYPES_HPP
#define SIMD_FIX_TYPES_HPP

#include <cstdint>
#include <string_view>

#include "org/limitless/fix/CodecTypes.hpp"

namespace org::limitless::fix {

struct Protocol
{
    enum Values
    {
        Null,
        FIXT_1_1,
        FIX_4_3,
        FIX_4_4,
        Max
    };
    static constexpr std::string_view Codes[4]  =
    {
        "?",
        "FIXT.1.1",
        "FIX.4.3",
        "FIX.4.4"
    };

    static constexpr auto code(const Values value)
    {
        return value >= Null && value < Max ? Codes[value] : Codes[0];
    }
};

inline constexpr FixedString FIXT_1_1 {"FIXT.1.1"};
inline constexpr FixedString FIX_4_3 {"FIX.4.3"};
inline constexpr FixedString FIX_4_4 {"FIX.4.4"};

} // namespace org::limitless::fix

namespace org::limitless::fix::messages {

struct Encryption
{
    enum Values
    {
        Null,
        None
    };
    static constexpr std::string_view Codes[2]  =
    {
        "?",
        "0"
    };
};

struct MessageType
{
    enum Values
    {
        Null,
        Logon,
        Logout,
        TestRequest,
        Heartbeat,
        ResendRequest,
        Reject,
        SequenceReset,
        NewOrderSingle,
        ExecutionReport
    };
    static constexpr std::string_view Codes[10]  =
    {
        "?",
        "A",
        "5",
        "1",
        "0",
        "2",
        "3",
        "4",
        "D",
        "8"
    };
};

struct SessionRejectReason
{
    enum Values
    {
        Null,
        InvalidTagNumber,
        RequiredTagMissing,
        TagNotDefinedForMessageType,
        UndefinedTag,
        TagSpecifiedWithoutValue,
        ValueIsIncorrect,
        IncorrectDataFormat,
        DecryptionProblem,
        SignatureProblem,
        CompIDProblem,
        SendingTimeAccuracyProblem,
        InvalidMsgType
    };
    static constexpr std::string_view Codes[13]  =
    {
        "?",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11"
    };
};

struct GapFillFlag
{
    enum Values
    {
        Null,
        GapFillMessage,
        SequenceReset
    };
    static constexpr std::string_view Codes[3]  =
    {
        "?",
        "Y",
        "N"
    };
};

struct Side
{
    enum Values
    {
        Null,
        Buy,
        Sell,
        BuyMinus,
        SellPlus,
        SellShort
    };
    static constexpr std::string_view Codes[6]  =
    {
        "?",
        "1",
        "2",
        "3",
        "4",
        "5"
    };
};

struct OrdType
{
    enum Values
    {
        Null,
        Market,
        Limit,
        Stop,
        StopLimit
    };
    static constexpr std::string_view Codes[5]  =
    {
        "?",
        "1",
        "2",
        "3",
        "4"
    };
};

struct TimeInForce
{
    enum Values
    {
        Null,
        Day,
        GoodTillCancel,
        AtTheOpening,
        ImmediateOrCancel,
        FillOrKill
    };
    static constexpr std::string_view Codes[6]  =
    {
        "?",
        "0",
        "1",
        "2",
        "3",
        "4"
    };
};

struct HandlInst
{
    enum Values
    {
        Null,
        AutoPrivate,
        AutoPublic,
        Manual
    };
    static constexpr std::string_view Codes[4]  =
    {
        "?",
        "1",
        "2",
        "3"
    };
};

struct ExecType
{
    enum Values
    {
        Null,
        New,
        DoneForDay,
        Canceled,
        Replaced,
        PendingCancel,
        Stopped,
        Rejected,
        Suspended,
        PendingNew,
        Calculated,
        Expired,
        Restated,
        PendingReplace,
        Trade,
        TradeCorrect,
        TradeCancel,
        OrderStatus
    };
    static constexpr std::string_view Codes[18]  =
    {
        "?",
        "0",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I"
    };
};

struct OrdStatus
{
    enum Values
    {
        Null,
        New,
        PartiallyFilled,
        Filled,
        DoneForDay,
        Canceled,
        Replaced,
        PendingCancel,
        Stopped,
        Rejected,
        Suspended,
        PendingNew,
        Calculated,
        Expired,
        PendingReplace
    };
    static constexpr std::string_view Codes[15]  =
    {
        "?",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "A",
        "B",
        "C",
        "E"
    };
};

struct Boolean
{
    enum Values
    {
        Null,
        Yes,
        No
    };
    static constexpr std::string_view Codes[3]  =
    {
        "?",
        "Y",
        "N"
    };
};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_TYPES_HPP
