// Generated by Generator from protocol.xml. Do not edit by hand.
#ifndef SIMD_FIX_TYPES_HPP
#define SIMD_FIX_TYPES_HPP

#include <cstdint>

namespace org::limitless::fix::messages {

struct Protocol
{
    enum Values
    {
        Null,
        FIX_1_1
    };
    static constexpr uint8_t Codes[2]  =
    {
        '?',
        'F'
    };
    Protocol() : m_value{Null} {}
    Values m_value;
};

struct Encryption
{
    enum Values
    {
        Null,
        None
    };
    static constexpr uint8_t Codes[2]  =
    {
        '?',
        '0'
    };
    Encryption() : m_value{Null} {}
    Values m_value;
};

struct MessageType
{
    enum Values
    {
        Null,
        Logon,
        Logout,
        TestRequest,
        Heartbeat
    };
    static constexpr uint8_t Codes[5]  =
    {
        '?',
        'A',
        '5',
        '1',
        '0'
    };
    MessageType() : m_value{Null} {}
    Values m_value;
};

} // namespace org::limitless::fix::messages

#endif //SIMD_FIX_TYPES_HPP
