//
// Created by Fredrik Dahlberg on 2026-06-06.
//

#include <filesystem>
#include <fstream>
#include <print>

#include "org/limitless/generator/fix/DataModel.hpp"

using namespace org::limitless::fix;
using namespace org::limitless::generator::fix;

static void generateTypes(const std::string& fileName,
                          const std::vector<Record>& enums);
static void generateDecoders(const std::string& fileName,
                             const std::vector<Record>& records);
static void generateEncoders(const std::string& fileName,
                             const std::vector<Record>& records);

static void generateMessageHandler(const std::string& fileName,
                                   const std::vector<Record>& records);

static void generateRecordDecoders(std::ostream& out, const Record& record);
static void generateRecordEncoders(std::ostream& out, const Record& record);

int main(int argc, char** argv)
{
    pugi::xml_document doc;
    const auto result = doc.load_file(argv[1]);
    if (argc != 3 || !result)
    {
        std::println("XML error: {}, dir = {}, file = {}", result.description(),
                     std::filesystem::current_path().c_str(), argv[1]);
        std::println("Usage: generator <protocol file> <output director>");
        return 1;
    }

    DataModel model{};
    model.process(doc);

    std::string typesFile{argv[2]};
    typesFile.append("/FixTypes.hpp");
    generateTypes(typesFile, model.m_enums);

    std::string decodersFile{argv[2]};
    decodersFile.append("/FixMessageDecoders.hpp");
    generateDecoders(decodersFile, model.m_records);

    std::string handlerFile{argv[2]};
    handlerFile.append("/FixMessageHandler.hpp");
    generateMessageHandler(handlerFile, model.m_records);

    std::string encodersFile{argv[2]};
    encodersFile.append("/FixMessageEncoders.hpp");
    generateEncoders(encodersFile, model.m_records);

    return 0;
}

static void generateEnums(std::ostream& out, const Record& record)
{
    out << std::format("struct {}\n", record.m_name);
    out << "{\n";
    const auto end = record.m_fields.end();
    out << "    enum Values\n    {\n";
    for (auto value = record.m_fields.begin(); value != end; ++value)
    {
        out << std::format("        {}{}\n", value->m_name, value != end - 1 ? "," : "");
    }
    out << "    };\n";

    auto size = record.m_fields.size();
    out << std::format("    static constexpr std::string_view Codes[{}]  =\n    {{\n", size);
    for (auto value = record.m_fields.begin(); value != end; ++value)
    {
        out << std::format("        \"{}\"{}\n", value->m_type, value != end - 1 ? "," : "");
    }
    out << "    };\n";
    out << "};\n\n";
}

static void generateTypes(const std::string& fileName,
                          const std::vector<Record>& enums)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Types/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_TYPES_HPP\n";
    out << "#define SIMD_FIX_TYPES_HPP\n\n";
    out << "#include <cstdint>\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    for (const auto& type: enums)
    {
        generateEnums(out, type);
    }
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif //SIMD_FIX_TYPES_HPP\n";

    out.close();
}

static void generateDecoders(const std::string& fileName,
                             const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Decoder/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_DECODERS_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_DECODERS_HPP\n\n";
    out << "#include <expected>\n\n";
    out << "#include \"org/limitless/fix/decoder/GroupDecoder.hpp\"\n";
    out << "#include \"org/limitless/fix/decoder/MessageDecoder.hpp\"\n";
    out << "#include \"org/limitless/fix/messages/FixTypes.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using namespace org::limitless::fix::decoder;\n\n";
    for (auto& record: records)
    {
        generateRecordDecoders(out, record);
    }
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif //SIMD_FIX_MESSAGE_DECODERS_HPP\n";

    out.close();
}

static void generateEncoders(const std::string& fileName,
                             const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Encoder/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_ENCODERS_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_ENCODERS_HPP\n\n";
    out << "#include <expected>\n\n";
    out << "#include \"org/limitless/fix/encoder/GroupEncoder.hpp\"\n";
    out << "#include \"org/limitless/fix/encoder/MessageEncoder.hpp\"\n";
    out << "#include \"org/limitless/fix/messages/FixTypes.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using namespace org::limitless::fix::encoder;\n\n";
    for (auto& record: records)
    {
        generateRecordEncoders(out, record);
    }
    out << "} // namespace org::limitless::fix::encoder\n\n";
    out << "#endif //SIMD_FIX_MESSAGE_ENCODERS_HPP\n";

    out.close();
}

static std::string uncap(const std::string& value)
{
    std::string result{value};
    if (!value.empty())
    {
        result[0] = static_cast<char>(std::tolower(static_cast<unsigned char>(result[0])));
    }
    return result;
}

static void generateMessageHandler(const std::string& fileName, const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Error: could not open '{}' for writing", fileName);
        return;
    }

    std::vector<Record> messages{};
    for (const auto& record: records)
    {
        if (!record.m_id.empty())
        {
            messages.push_back(record);
        }
    }
    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_HANDLER_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_HANDLER_HPP\n\n";
    out << "#include \"org/limitless/fix/CodecTypes.hpp\"\n";
    out << "#include \"org/limitless/fix/messages/FixMessageDecoders.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using fix::Result;\n\n";
    out << "template <typename Handler>\n";
    out << "class MessageHandler\n{\n";
    for (auto& message: messages)
    {
        out << std::format("    {}Decoder m_{};\n", message.m_name, uncap(message.m_name));
    }
    out << "\npublic:\n";
    out << "    template <typename Event>\n";
    out << "    Result::Values receive(Event&& event)\n";
    out << "    {\n";
    out << "        return static_cast<Handler*>(this)->handle(std::forward<Event>(event));\n";
    out << "    }\n\n";
    out << "    void setSessionContext(const SessionContext& context)\n";
    out << "    {\n";
    for (auto& message: messages)
    {
        out << std::format("        m_{}.context(&context);\n", uncap(message.m_name));
    }
    out << "    }\n\n";
    out << "    Result::Values handle(const std::span<const uint8_t> data,\n";
    out << "                          const std::span<Token> tokens,\n";
    out << "                          const std::span<uint16_t> tags,\n";
    out << "                          const uint32_t count,\n";
    out << "                          const uint8_t messageType)\n";
    out << "    {\n";
    out << "        auto status = Result::InvalidMessageType;\n";
    out << "        switch (messageType)\n";
    out << "        {\n";
    for (auto& message: messages)
    {
        auto memberName = uncap(message.m_name);
        out << std::format("            case {}Decoder::MessageId:\n", message.m_name);
        out << std::format("                m_{}.wrap(data, tokens, tags, count);\n", memberName);
        out << std::format("                status = m_{}.checkRequired();\n", memberName);
        out << "                if (status == Result::Success)\n";
        out << "                {\n";
        out << std::format("                    status = receive(m_{});\n", memberName);
        out << "                }\n";
        out << "                break;\n";
    }
    out << "            default:\n";
    out << "                break;\n";
    out << "        }\n";
    out << "        return status;\n";
    out << "    }\n\n";
    out << "protected:\n";
    for (auto& message: messages)
    {
        out << std::format("    Result::Values handle({}Decoder&) {{ return Result::Success; }}\n", message.m_name);
    }
    out << "};\n\n";
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif // SIMD_FIX_MESSAGE_HANDLER_HPP\n";
}

static void generateDecoderConstructors(std::ostream& out, const Record& record, const std::string& codec)
{
    if (!record.m_records.empty())
    {
        out << "public:\n";
    }
    if (record.m_parent == ParentType::Message)
    {
        out << std::format("    {}{}() : \n", record.m_name, codec);
    } else
    {
        out << std::format("    explicit {}{}(Field{}& {}) : \n", record.m_name, codec, codec, uncap(codec));
    }

    if (record.m_parent == ParentType::Component || record.m_parent == ParentType::Group)
    {
        out << std::format("        {}{}{{{}}}{}\n",
                           ParentType::name(record.m_parent), codec, uncap(codec),
                           record.m_records.empty() ? "" : ",");
    }
    if (!record.m_records.empty())
    {
        const auto& back = record.m_records.back();
        for (auto const& field: record.m_records)
        {
            out << std::format("        m_{}{{{}{}}}{}\n",
                               uncap(field.m_name), record.m_parent == ParentType::Message ? "m_" : "",
                               uncap(codec), field.m_name != back.m_name ? "," : "");
        }
    }
    if (!record.m_records.empty() || record.m_parent == ParentType::Group)
    {
        out << "    {\n    }\n\n";

        const auto name = std::format("{}{}", record.m_name, codec);
        out << std::format("    {}(const {}&) = delete;\n", name, name);
        out << std::format("    {}& operator=(const {}&) = delete;\n", name, name);
        out << std::format("    {}({}&&) = delete;\n", name, name);
        out << std::format("    {}& operator=({}&&) = delete;\n\n", name, name);
    }
}

static void generateStructFields(std::ostream& out, const Record& record, const std::string& codec)
{
    if (record.m_records.size() >= 1)
    {
        out << "private:\n";
        for (auto& comp: record.m_records)
        {
            out << std::format("    {}{} m_{};\n\n", comp.m_type, codec, uncap(comp.m_name));
        }
    }
}

static void generateWrapNext(std::ostream& out, const Record& record)
{
    if (record.m_parent == ParentType::Message)
    {
        out << std::format("    {}Decoder& wrap(", record.m_name);
        out << "const std::span<const uint8_t> data,\n";
        out << "            const std::span<Token> tokens,\n";
        out << "            const std::span<uint16_t> tags,\n";
        out << "            const uint32_t count)\n";
        out << "    {\n";
        out << "        m_decoder.wrap(data, tokens, tags, count);\n";
        out << "        return *this;\n";
        out << "    }\n\n";

        out << "    void context(SessionContext& context)\n";
        out << "    {\n";
        out << "        MessageDecoder::context(context);\n";
        out << "    }\n\n";
    } else if (record.m_parent == ParentType::Group)
    {
        out << std::format("    {}Decoder& wrap()\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupDecoder::wrap({});\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";

        out << std::format("    {}Decoder& next()\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupDecoder::next();\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";
    }
}

static void generateGetters(std::ostream& out, const Record& record)
{
    auto parent = ParentType::name(record.m_parent);
    for (const auto& field: record.m_fields)
    {
        auto methodName = field.m_name;
        methodName[0] = static_cast<char>(std::tolower(static_cast<unsigned char>(methodName[0])));
        auto category = field.m_category;
        if (field.m_category != Category::Counter && field.m_category != Category::Struct)
        {
            const auto isEnum = field.m_category == Category::Enum;
            const auto mandatory = std::string{field.m_presence == Presence::Required ? "true" : "false"};
            out << std::format("    [[nodiscard]] std::expected<{}, Result::Values> {}() const\n",
                               isEnum ? std::format("{}::Values", field.m_type) : Category::type(category), methodName);
            out << "    {\n";
            std::string arg = isEnum ? std::format(", {}", field.m_type) : "";
            out << std::format("        return m_decoder.get{}<{}, {}{}, ParentType::{}>();\n",
                               Category::name(category), field.m_tag, mandatory, arg, parent);
            out << "    }\n\n";
        }
    }
    for (const auto& comp: record.m_records)
    {
        auto fieldName = uncap(comp.m_name);
        out << std::format("    {}Decoder& {}()\n    {{\n", comp.m_type, fieldName);
        out << std::format("        return m_{}", fieldName);
        if (comp.m_tag != 0)
        {
            out << std::format(".wrap()");
        }
        out << ";\n";
        out << std::format("    }}\n\n");
    }
}

static void generateSetters(std::ostream& out, const Record& record)
{
    auto parent = ParentType::name(record.m_parent);
    for (const auto& field: record.m_fields)
    {
        auto methodName = field.m_name;
        methodName[0] = static_cast<char>(std::tolower(static_cast<unsigned char>(methodName[0])));
        auto category = field.m_category;
        if (field.m_category != Category::Counter && field.m_category != Category::Struct)
        {
            const auto isEnum = field.m_category == Category::Enum;
            const auto mandatory = std::string{field.m_presence == Presence::Required ? "true" : "false"};
            out << std::format("    {}& {}(const {}& value)\n",
                               isEnum ? field.m_type : Category::type(category), methodName, field.m_type);
            out << "    {\n";
            std::string arg = isEnum ? std::format(", {}", field.m_type) : "";
            out << std::format("        m_encoder.set{}<{}, {}{}, ParentType::{}>(value);\n",
                               Category::name(category), field.m_tag, mandatory, arg, parent);
            out << "        return *this;\n";
            out << "    }\n\n";
        }
    }
    for (const auto& comp: record.m_records)
    {
        auto fieldName = uncap(comp.m_name);
        out << std::format("    {}Encoder& {}()\n    {{\n", comp.m_type, fieldName);
        out << std::format("        return m_{}", fieldName);
        if (comp.m_tag != 0)
        {
            out << std::format(".wrap()");
        }
        out << ";\n";
        out << std::format("    }}\n\n");
    }
}

static void generateRecordDecoders(std::ostream& out, const Record& record)
{
    out << std::format("struct {}Decoder : ", record.m_name);
    out << std::format("{}Decoder\n{{\n", ParentType::name(record.m_parent));

    generateStructFields(out, record, "Decoder");
    generateDecoderConstructors(out, record, "Decoder");
    if (record.m_parent == ParentType::Message)
    {
        out << std::format("    static constexpr uint16_t MessageId = '{}';\n\n", record.m_id);
    }
    generateWrapNext(out, record);
    generateGetters(out, record);
    out << "};\n\n";
}

static void generateRecordEncoders(std::ostream& out, const Record& record)
{
    out << std::format("struct {}Encoder : ", record.m_name);
    out << std::format("{}Encoder\n{{\n", ParentType::name(record.m_parent));

    generateStructFields(out, record, "Encoder");
    generateDecoderConstructors(out, record, "Encoder");
    if (record.m_parent == ParentType::Message)
    {
        out << std::format("    static constexpr uint16_t MessageId = '{}';\n\n", record.m_id);
    }
    // generateWrapNext(out, record);
    generateSetters(out, record);
    out << "};\n\n";
}
