//
// Created by Fredrik Dahlberg on 2026-06-06.
//

#include <filesystem>
#include <fstream>
#include <print>

#include "org/limitless/generator/fix/DataModel.hpp"

using namespace org::limitless::fix;
using namespace org::limitless::generator::fix;

static void generateTypes(const std::string& fileName,
                          const Record& protocol,
                          const std::vector<Record>& enums);
static void generateDecoders(const std::string& fileName,
                             const std::vector<Record>& records);
static void generateEncoders(const std::string& fileName,
                             const std::vector<Record>& records);

static void generateMessageHandler(const std::string& fileName,
                                   const std::vector<Record>& records);

static void generateRecordDecoders(std::ostream& out, const Record& record);
static void generateRecordEncoders(std::ostream& out, const Record& record);

int main(int argc, char** argv)
{
    pugi::xml_document doc;
    const auto result = doc.load_file(argv[1]);
    if (argc != 3 || !result)
    {
        std::println("XML error: {}, dir = {}, file = {}", result.description(),
                     std::filesystem::current_path().c_str(), argv[1]);
        std::println("Usage: generator <protocol file> <output director>");
        return 1;
    }

    DataModel model{};
    model.process(doc);

    std::string typesFile{argv[2]};
    typesFile.append("/FixTypes.hpp");
    generateTypes(typesFile, model.m_protocol, model.m_enums);

    std::string decodersFile{argv[2]};
    decodersFile.append("/FixMessageDecoders.hpp");
    generateDecoders(decodersFile, model.m_records);

    std::string handlerFile{argv[2]};
    handlerFile.append("/FixMessageHandler.hpp");
    generateMessageHandler(handlerFile, model.m_records);

    std::string encodersFile{argv[2]};
    encodersFile.append("/FixMessageEncoders.hpp");
    generateEncoders(encodersFile, model.m_records);

    return 0;
}

static void generateEnums(std::ostream& out, const Record& record)
{
    out << std::format("struct {}\n", record.m_name);
    out << "{\n";
    const auto end = record.m_fields.end();
    out << "    enum Values\n    {\n";
    for (auto value = record.m_fields.begin(); value != end; ++value)
    {
        out << std::format("        {}{}\n", value->m_name, value != end - 1 ? "," : "");
    }
    out << "    };\n";

    auto size = record.m_fields.size();
    out << std::format("    static constexpr std::string_view Codes[{}]  =\n    {{\n", size);
    for (auto value = record.m_fields.begin(); value != end; ++value)
    {
        out << std::format("        \"{}\"{}\n", value->m_type, value != end - 1 ? "," : "");
    }
    out << "    };\n";
    out << "};\n\n";
}

static void generateProtocol(std::ostream& out, const Record& protocol)
{
    out << "namespace org::limitless::fix {\n\n";
    out << "struct Protocol\n{\n";
    out << "    enum Values\n    {\n";
    for (const auto& field : protocol.m_fields)
    {
        out << std::format("        {},\n", field.m_name);
    }
    out << "        Max\n";
    out << "    };\n";

    auto size = protocol.m_fields.size();
    out << std::format("    static constexpr std::string_view Codes[{}]  =\n    {{\n", size);
    const auto end = protocol.m_fields.end();
    for (auto value = protocol.m_fields.begin(); value != end; ++value)
    {
        out << std::format("        \"{}\"{}\n", value->m_type, value != end - 1 ? "," : "");
    }
    out << "    };\n\n";
    out << "    static constexpr auto code(const Values value)\n";
    out << "    {\n";
    out << "        return value >= Null && value < Max ? Codes[value] : Codes[0];\n";
    out << "    }\n";
    out << "};\n\n";
    for (const auto& field : protocol.m_fields)
    {
        if (field.m_name != "Null")
        {
            out << std::format("inline constexpr FixedString {} {{\"{}\"}};\n",
                               field.m_name, field.m_type);
        }
    }
    out << "\n} // namespace org::limitless::fix\n\n";
}

static void generateTypes(const std::string& fileName,
                          const Record& protocol,
                          const std::vector<Record>& enums)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Types/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_FIX_TYPES_HPP\n";
    out << "#define SIMD_FIX_FIX_TYPES_HPP\n\n";
    out << "#include <cstdint>\n";
    out << "#include <string_view>\n\n";
    out << "#include \"org/limitless/fix/Types.hpp\"\n\n";
    generateProtocol(out, protocol);
    out << "namespace org::limitless::fix::messages {\n\n";
    for (const auto& type: enums)
    {
        generateEnums(out, type);
    }
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif //SIMD_FIX_TYPES_HPP\n";

    out.close();
}

static void generateDecoders(const std::string& fileName,
                             const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Decoder/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_DECODERS_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_DECODERS_HPP\n\n";
    out << "#include \"org/limitless/fix/detail/Expected.hpp\"\n\n";
    out << "#include \"org/limitless/fix/decoder/DataDecoder.hpp\"\n";
    out << "#include \"org/limitless/fix/decoder/GroupDecoder.hpp\"\n";
    out << "#include \"org/limitless/fix/decoder/MessageDecoder.hpp\"\n";
    out << "#include \"org/limitless/fix/messages/FixTypes.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using namespace org::limitless::fix::decoder;\n\n";
    for (auto& record: records)
    {
        generateRecordDecoders(out, record);
    }
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif //SIMD_FIX_MESSAGE_DECODERS_HPP\n";

    out.close();
}

static void generateEncoders(const std::string& fileName,
                             const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Encoder/Error: could not open '{}' for writing", fileName);
        return;
    }

    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_ENCODERS_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_ENCODERS_HPP\n\n";
    out << "#include \"org/limitless/fix/encoder/DataEncoder.hpp\"\n";
    out << "#include \"org/limitless/fix/encoder/GroupEncoder.hpp\"\n";
    out << "#include \"org/limitless/fix/encoder/MessageEncoder.hpp\"\n";
    out << "#include \"org/limitless/fix/encoder/PayloadEncoder.hpp\"\n\n";
    out << "#include \"org/limitless/fix/messages/FixTypes.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using namespace org::limitless::fix::encoder;\n\n";
    for (auto& record: records)
    {
        generateRecordEncoders(out, record);
    }

    out << "template <FixedString Protocol, FixedString Target, FixedString Sender>\n";
    out << "class FixPayloadEncoder\n";
    out << "{\n";
    out << "    PayloadEncoder<Protocol, Target, Sender> m_encoder;\n";
    out << "public:\n";
    out << "    FixPayloadEncoder() = default;\n\n";

    out << "    FixPayloadEncoder& wrap(const uint32_t offset, const std::span<uint8_t> data)\n";
    out << "    {\n";
    out << "        m_encoder.wrap(offset, data);\n";
    out << "        return *this;\n";
    out << "    }\n\n";

    out << "    [[nodiscard]] uint32_t offset() const\n";
    out << "    {\n";
    out << "        return m_encoder.offset();\n";
    out << "    }\n\n";

    out << "    template <typename MessageEncoderType>\n";
    out << "    MessageEncoderType& wrapMessage(MessageEncoderType& message) const\n";
    out << "    {\n";
    out << "        return m_encoder.wrapMessage(message);\n";
    out << "    }\n\n";

    out << "    template <EncodableMessage Message>\n";
    out << "    uint32_t encode(const Message& message)\n";
    out << "    {\n";
    out << "        return m_encoder.encode(message);\n";
    out << "    }\n\n";

    out << "    [[nodiscard]] uint32_t encodedLength() const\n";
    out << "    {\n";
    out << "        return m_encoder.encodedLength();\n";
    out << "    }\n";

    out << "};\n\n";
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif //SIMD_FIX_MESSAGE_ENCODERS_HPP\n";

    out.close();
}

static std::string uncap(const std::string& value)
{
    std::string result{value};
    if (!value.empty())
    {
        result[0] = static_cast<char>(std::tolower(static_cast<unsigned char>(result[0])));
    }
    return result;
}

static void generateMessageHandler(const std::string& fileName, const std::vector<Record>& records)
{
    std::ofstream out(fileName);
    if (!out)
    {
        std::println("Error: could not open '{}' for writing", fileName);
        return;
    }

    std::vector<Record> messages{};
    for (const auto& record: records)
    {
        if (!record.m_id.empty())
        {
            messages.push_back(record);
        }
    }
    out << "// Generated by Generator from protocol.xml. Do not edit by hand.\n";
    out << "#ifndef SIMD_FIX_MESSAGE_HANDLER_HPP\n";
    out << "#define SIMD_FIX_MESSAGE_HANDLER_HPP\n\n";
    out << "#include \"org/limitless/fix/detail/Tokens.hpp\"\n";
    out << "#include \"org/limitless/fix/messages/FixMessageDecoders.hpp\"\n\n";
    out << "namespace org::limitless::fix::messages {\n\n";
    out << "using fix::Result;\n\n";
    out << "template <typename Handler>\n";
    out << "class MessageHandler\n{\n";
    out << "    const SessionContext* m_context{};\n\n";
    out << "public:\n";
    out << "    template <typename Event>\n";
    out << "    Result receive(Event&& event)\n";
    out << "    {\n";
    out << "        return static_cast<Handler*>(this)->handle(std::forward<Event>(event));\n";
    out << "    }\n\n";
    out << "    void setSessionContext(const SessionContext& context)\n";
    out << "    {\n";
    out << "        m_context = &context;\n";
    out << "    }\n\n";
    out << "    Result handle(const detail::TokenizedMessage& message,\n";
    out << "                  const uint16_t messageType)\n";
    out << "    {\n";
    out << "        auto status = Result::InvalidMessageType;\n";
    out << "        switch (messageType)\n";
    out << "        {\n";
    for (auto& message: messages)
    {
        // LogonDecoder logon;
        // logon.context(m_context);
        // logon.wrap(message);
        auto localName = uncap(message.m_name);
        out << std::format("            case {}Decoder::MessageId:\n", message.m_name);
        out << "            {\n";
        out << std::format("                {}Decoder {}{{m_context, message}};\n", message.m_name, localName);
        //out << std::format("                {}.context(m_context);\n", localName);
        //out << std::format("                {}.wrap(message);\n", localName);
        out << std::format("                status = {}.validate();\n", localName);
        out << "                if (status == Result::Success)\n";
        out << "                {\n";
        out << std::format("                    status = receive({});\n", localName);
        out << "                }\n";
        out << "                break;\n";
        out << "            }\n";
    }
    out << "            default:\n";
    out << "                break;\n";
    out << "        }\n";
    out << "        return status;\n";
    out << "    }\n\n";
    out << "protected:\n";
    for (auto& message: messages)
    {
        out << std::format("    Result handle({}Decoder&) {{ return Result::Success; }}\n", message.m_name);
    }
    out << "};\n\n";
    out << "} // namespace org::limitless::fix::messages\n\n";
    out << "#endif // SIMD_FIX_MESSAGE_HANDLER_HPP\n";
}

static void generateConstructors(std::ostream& out, const Record& record, const std::string& codec)
{
    if (!record.m_records.empty())
    {
        out << "public:\n";
    }
    if (record.m_parent == RecordType::Message)
    {
        out << std::format("    {}{}() : \n", record.m_name, codec);
    }
    else
    {
        out << std::format("    explicit {}{}(Field{}& {}) : \n", record.m_name, codec, codec, uncap(codec));
    }
    if (record.m_parent == RecordType::Component || record.m_parent == RecordType::Group)
    {
        out << std::format("        {}{}{{{}}}{}\n",
                           name(record.m_parent), codec, uncap(codec),
                           record.m_records.empty() ? "" : ",");
    }
    if (!record.m_records.empty())
    {
        const auto& back = record.m_records.back();
        for (auto const& field: record.m_records)
        {
            out << std::format("        m_{}{{{}{}}}{}\n",
                               uncap(field.m_name), record.m_parent == RecordType::Message ? "m_" : "",
                               uncap(codec), field.m_name != back.m_name ? "," : "");
        }
    }
    out << "    {\n    }\n\n";

    if (record.m_parent == RecordType::Message && codec == "Decoder")
    {
        out << std::format("    {}{}(const SessionContext* context, const TokenizedMessage& message)\n", record.m_name, codec);
        out << std::format("        : {}{}{{}}\n", record.m_name, codec);
        out << "    {\n";
        out << std::format("        Message{}::wrap(message);\n", codec);
        out << std::format("        Message{}::context(context);\n", codec);
        out << "    }\n\n";
    }

    if (!record.m_records.empty() || record.m_parent == RecordType::Group)
    {
        const auto name = std::format("{}{}", record.m_name, codec);
        out << std::format("    {}(const {}&) = delete;\n", name, name);
        out << std::format("    {}& operator=(const {}&) = delete;\n", name, name);
        out << std::format("    {}({}&&) = delete;\n", name, name);
        out << std::format("    {}& operator=({}&&) = delete;\n\n", name, name);
    }
}

static bool isCacheableField(const org::limitless::generator::fix::Field& field)
{
    return field.m_category != Category::Counter &&
           field.m_category != Category::Struct &&
           field.m_tag != 8 && field.m_tag != 9 && field.m_tag != 35;
}

static bool isRequiredCacheableField(const org::limitless::generator::fix::Field& field)
{
    return field.m_presence == Presence::Required && isCacheableField(field);
}

static std::string fieldReturnType(const org::limitless::generator::fix::Field& field)
{
    const auto isEnum = field.m_category == Category::Enum;
    return isEnum ? std::format("{}::Values", field.m_type)
                  : std::string{type(field.m_category)};
}

static std::string decoderCall(const org::limitless::generator::fix::Field& field, const Record& record)
{
    const auto parent = name(record.m_parent);
    const auto isEnum = field.m_category == Category::Enum;
    const auto mandatory = std::string{field.m_presence == Presence::Required ? "true" : "false"};
    std::string arg = isEnum ? std::format(", {}", field.m_type) : "";
    return std::format("m_decoder.get{}<{}, {}{}, RecordType::{}>()",
                       name(field.m_category), field.m_tag, mandatory, arg, parent);
}

static void generateStructFields(std::ostream& out, const Record& record, const std::string& codec)
{
    bool hasPrivate = !record.m_records.empty();
    if (hasPrivate)
    {
        out << "private:\n";
        for (auto& comp: record.m_records)
        {
            out << std::format("    {}{} m_{};\n\n", comp.m_type, codec, uncap(comp.m_name));
        }
    }

    if (codec == "Decoder" && record.m_parent == RecordType::Message)
    {
        bool first = true;
        for (const auto& field : record.m_fields)
        {
            if (isCacheableField(field))
            {
                if (!hasPrivate && first)
                {
                    out << "private:\n";
                    hasPrivate = true;
                }
                first = false;
                out << std::format("    int8_t m_{}Index{{-1}};\n", uncap(field.m_name));
            }
        }
        if (!first)
        {
            out << "\n";
        }
    }
}

static void generateWrapNextDecoders(std::ostream& out, const Record& record)
{
    if (record.m_parent == RecordType::Group)
    {
        out << std::format("    {}Decoder& wrap()\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupDecoder::wrap<{}>();\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";

        out << std::format("    {}Decoder& next()\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupDecoder::next();\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";
    }
}

static void generateWrapNextEncoders(std::ostream& out, const Record& record)
{
    if (record.m_parent == RecordType::Message)
    {
        out << std::format("    {}Encoder& wrap(const std::span<uint8_t> data, const uint32_t offset = 0)\n", record.m_name);
        out << "    {\n";
        out << "        MessageEncoder::wrap(data, offset);\n";
        out << "        return *this;\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::string_view type() const\n";
        out << "    {\n";
        out << "        return MessageId;\n";
        out << "    }\n\n";
    }
    else if (record.m_parent == RecordType::Group)
    {
        out << std::format("    {}Encoder& wrap(const uint32_t count)\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupEncoder::wrap({}, count);\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";

        out << std::format("    {}Encoder& next()\n", record.m_name);
        out << "    {\n";
        out << std::format("        GroupEncoder::next();\n", record.m_tag);
        out << "        return *this;\n";
        out << "    }\n\n";
    }
}

static void generateGetters(std::ostream& out, const Record& record)
{
    for (const auto& field: record.m_fields)
    {
        auto methodName = field.m_name;
        methodName[0] = static_cast<char>(std::tolower(static_cast<unsigned char>(methodName[0])));
        if (field.m_category != Category::Counter && field.m_category != Category::Struct)
        {
            out << std::format("    [[nodiscard]] expected<{}, Result> {}() const\n",
                               fieldReturnType(field), methodName);
            out << "    {\n";
            if (record.m_parent == RecordType::Message && isCacheableField(field))
            {
                const auto memberName = uncap(field.m_name);
                const auto optional = field.m_presence != Presence::Required;
                if (optional)
                {
                    out << std::format("        if (m_{}Index < 0)\n", memberName);
                    out << "        {\n";
                    out << "            return unexpected{Result::Success};\n";
                    out << "        }\n";
                }
                if (field.m_category == Category::Enum)
                {
                    out << std::format("        return m_decoder.enumAt<{}>(m_{}Index);\n",
                                       field.m_type, memberName);
                }
                else if (field.m_category == Category::UTCTimeOnly)
                {
                    out << std::format("        return m_decoder.timeOnlyAt(m_{}Index);\n", memberName);
                }
                else if (field.m_category == Category::UTCDateOnly)
                {
                    out << std::format("        return m_decoder.dateOnlyAt(m_{}Index);\n", memberName);
                }
                else
                {
                    out << std::format("        return m_decoder.valueAt<{}>(m_{}Index);\n",
                                       fieldReturnType(field), memberName);
                }
            }
            else
            {
                out << std::format("        return {};\n", decoderCall(field, record));
            }
            out << "    }\n\n";
        }
    }
    for (const auto& comp: record.m_records)
    {
        auto fieldName = uncap(comp.m_name);
        if (comp.m_category == Category::Data)
        {
            out << std::format("    [[nodiscard]] DataDecoder& {}()\n    {{\n", fieldName);
            out << std::format("        return m_{}.wrap<{}, {}>();\n",
                               fieldName, comp.m_length, comp.m_tag);
            out << std::format("    }}\n\n");
        }
        else
        {
            out << std::format("    [[nodiscard]] {}Decoder& {}()\n    {{\n", comp.m_type, fieldName);
            out << std::format("        return m_{}", fieldName);
            if (comp.m_tag != 0)
            {
                out << std::format(".wrap()");
            }
            out << ";\n";
            out << std::format("    }}\n\n");
        }
    }
}

static void generateFieldEncoders(std::ostream& out, const Record& record)
{
    for (const auto& field: record.m_fields)
    {
        if (field.m_tag != 8 && field.m_tag != 9 && field.m_tag != 10 &&
            field.m_tag != 35 && field.m_tag != 49 && field.m_tag != 56 &&
            field.m_category != Category::Counter && field.m_category != Category::Struct)
        {
            const auto isEnum = field.m_category == Category::Enum;
            const auto category = isEnum ?
                                      std::format("{}::Values", field.m_type) :
                                      std::string{type(field.m_category)};
            out << std::format("    {}Encoder& {}(const {} value)\n",
                               record.m_name, uncap(field.m_name), category);
            out << "    {\n";
            if (isEnum)
            {
                const auto required = field.m_presence == Presence::Required ? "true" : "false";
                out << std::format("        m_encoder.encode<\"{}\", {}, {}>(value);\n",
                                   field.m_tag, required, field.m_type);
            }
            else if (field.m_category == Category::Decimal)
            {
                out << std::format("        m_encoder.encode<\"{}\">(value);\n",
                                   field.m_tag);
            }
            else if (field.m_category == Category::UTCTimeOnly)
            {
                out << std::format("        m_encoder.encodeUTCTimeOnly<\"{}\">(value);\n",
                                   field.m_tag);
            }
            else if (field.m_category == Category::UTCDateOnly)
            {
                out << std::format("        m_encoder.encodeUTCDateOnly<\"{}\">(value);\n",
                                   field.m_tag);
            }
            else
            {
                out << std::format("        m_encoder.encode<\"{}\", {}>(value);\n",
                                   field.m_tag, type(field.m_category));
            }
            out << "        return *this;\n";
            out << "    }\n\n";
        }
    }
    for (const auto& comp: record.m_records)
    {
        const auto fieldName = uncap(comp.m_name);
        if (comp.m_category == Category::Data)
        {
            out << std::format("    {}Encoder& {}(const std::span<const uint8_t> data)\n",
                               record.m_name, fieldName);
            out << "    {\n";
            out << std::format("        m_{}.encode<\"{}\", \"{}\">(data);\n",
                               fieldName, comp.m_length, comp.m_tag);
            out << "        return *this;\n";
            out << "    }\n\n";
        }
        else
        {
            const auto group = comp.m_tag != 0;
            out << std::format("    {}Encoder& {}(", comp.m_type, fieldName);
            if (group)
            {
                out << "const uint32_t count";
            }
            out << ")\n    {\n";
            out << std::format("        return m_{}", fieldName);
            if (group)
            {
                out << ".wrap(count)";
            }
            out << ";\n    }\n\n";
        }
    }
}

static constexpr std::pair<int32_t, std::string_view> HeaderErrorCodes[] = {
    {49, "InvalidSenderCompId"},
    {56, "InvalidTargetCompId"},
    {34, "InvalidSequenceNumber"},
    {52, "InvalidSendingTime"},
};

static std::string_view headerErrorCode(const int32_t tag)
{
    for (const auto& [t, code] : HeaderErrorCodes)
    {
        if (t == tag)
        {
            return code;
        }
    }
    return {};
}

static void generateCheckRequired(std::ostream& out, const Record& record)
{
    if (record.m_parent != RecordType::Message)
    {
        return;
    }

    out << "    [[nodiscard]] Result validate()\n";
    out << "    {\n";

    for (const auto& field : record.m_fields)
    {
        if (!isRequiredCacheableField(field))
        {
            continue;
        }
        const auto memberName = uncap(field.m_name);
        const auto errorCode = headerErrorCode(field.m_tag);
        const auto resultName = errorCode.empty() ? "RequiredFieldMissing" : std::string{errorCode};
        out << std::format("        m_{}Index = static_cast<int8_t>(m_decoder.findIndex<{}, RecordType::Message>());\n",
                           memberName, field.m_tag);
        out << std::format("        if (m_{}Index < 0)\n", memberName);
        out << "        {\n";
        out << std::format("            return Result::{};\n", resultName);
        out << "        }\n";
    }

    for (const auto& field : record.m_fields)
    {
        if (field.m_presence == Presence::Required || !isCacheableField(field))
        {
            continue;
        }
        const auto memberName = uncap(field.m_name);
        out << std::format("        m_{}Index = static_cast<int8_t>(m_decoder.findIndex<{}, RecordType::Message>());\n",
                           memberName, field.m_tag);
    }

    out << "        return validateSession();\n";
    out << "    }\n\n";
}

static void generateRecordDecoders(std::ostream& out, const Record& record)
{
    out << std::format("struct {}Decoder : ", record.m_name);
    out << std::format("{}Decoder\n{{\n", name(record.m_parent));

    generateStructFields(out, record, "Decoder");
    generateConstructors(out, record, "Decoder");
    if (record.m_parent == RecordType::Message)
    {
        if (record.m_id.size() == 1)
        {
            out << std::format("    static constexpr uint16_t MessageId = '{}';\n\n", record.m_id);
        }
        else
        {
            out << std::format("    static constexpr uint16_t MessageId = '{}' | ('{}' << 8);\n\n",
                               record.m_id[0], record.m_id[1]);
        }
    }
    generateWrapNextDecoders(out, record);
    generateCheckRequired(out, record);
    generateGetters(out, record);
    out << "};\n\n";
}

static void generateRecordEncoders(std::ostream& out, const Record& record)
{
    out << std::format("struct {}Encoder : ", record.m_name);
    out << std::format("{}Encoder\n{{\n", name(record.m_parent));

    generateStructFields(out, record, "Encoder");
    generateConstructors(out, record, "Encoder");
    if (record.m_parent == RecordType::Message)
    {
        out << std::format("    static constexpr std::string_view MessageId = \"{}\";\n\n", record.m_id);
    }
    generateWrapNextEncoders(out, record);
    generateFieldEncoders(out, record);
    out << "};\n\n";
}